---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-bind-credentials
  labels:
    secrets.stackable.tech/class: openldap-bind-credentials
stringData:
  # User and password are defined in the OpenLDAP StatefulSet
  user: cn=ldapadmin,dc=example,dc=org
  password: ldapadminpassword