---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-bind-credentials
  labels:
    secrets.stackable.tech/class: openldap-bind-credentials  # <1>
stringData:
  user: cn=ldapadmin,dc=example,dc=org  # <2>
  password: ldapadminpassword           # <3>
  