---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: openldap  # <1>
spec:
  provider:
    ldap:
      hostname: openldap.default.svc.cluster.local  # <2>
      searchBase: ou=users,dc=example,dc=org
      bindCredentials:
        secretClass: openldap-bind-credentials  # <3>
      port: 1636
      tls:
        verification:
          server:
            caCert:
              secretClass: openldap-tls