= Contributors guide

== Introduction

Welcome to Stackable!

This document will show you the steps needed to contribute to the Stackable platform. Contributions can come in many shapes and forms but in this document we'll focus on code and documentation improvements. We'll assume you already know what the Stackable platform is and have a specific issue that you want solved.

This document should get you up and running with your development environment quickly.

== Contribution Workflow

The development of the Stackable platform takes place on https://github.com/stackabletech[GitHub]. On GitHub, each repository has it's own Issue-Tracker and since Stackable is a platform, there are several repositories where issues and pull-requests can be made. If you already have a good ideea where the issue or pull-request belongs, then you can skip reading to the contribution steps below. Otherwise you might want to a have a look at the <<Repo Walkthrough>> section below for hints.


Contribution steps:

1. Lookup if an existing issue already covers your problem
2. Submit a new issue and/or pull-request
3. Respond to questions or feedback
4. Improve your submission if necessary
5. Closing your contribution

Before submitting a new Issue or Pull-Request, it's always a good idea to check if the issue has already been discussed in the passt and if there is a resolution for it. If that is the case, consider contributing to the existing issue by either adding new feedback or code.

When creating a new Issue please provide as much information as you consider relevant. Issues can be Bug-Reports, Feature-Requests and so on. The Stackable repositories provide templates to make it easyer to submit high-quality Issues.  

When submitting a Pull-Request, you might be interested in knowing about the necessary <<Development Environment>>.

== Repo Walkthrough

This is quick walk through the most important git repositories:

=== Repository: https://github.com/stackabletech/issues[issues]

This repository exists solely for the purpose of tracking Issues related to the Stackable Platform in general. Large topics that impact many or even all of the plattform components are discussed here. There is no code in this repository.

=== Repository: https://github.com/stackabletech/documentation[documentation]

Platform wide documentation, such as this page, are hosted here. Also this repository has references to documentation that is hosted in individual <<Operator Repositories>>. It is the main source from which the public https://docs.stackable.tech/[Documentation] page is generated.

=== Repository: https://github.com/stackabletech/docker-images[docker-images]

The Stackable Platform can be used to install and run up several open-source products such as https://kafka.apache.org[Apache Kafka] or https://trino.io[Trino]. Container images of these products hosted on the https://repo.stackable.tech/[Stackable Repository Manager] and the sources hosted in this repository.

NOTE: Operators host their `Dockerfile`s in their own repository. 

=== Repository: https://github.com/stackabletech/integration-tests[integration-tests]

The Stackable Operators are tested in many environments and across cloud providers. Integration tests are currently driven by `Kuttl` and are hosted here.

=== Repository: https://github.com/stackabletech/t2[t2]

Integration testing across different versions and cloud providers is being developed here.

=== Operator Repositories

At the core of the Stackable Platform are Kubernetes operators used to install and manage various data products. Each operator has it's own repository and therefore it's own Issue Tracker and build pipeline. Every operator repository contains:

* The operator's source code
* One or more Custom Resource Definitions owned by the operator
* `Helm` chart
* Documentation
* `Dockerfile` and related artifacts to generate the operator image

== Development Environment

In order to contribute source code, you need an environment that is capable of running the following tools:

* Docker
* Kind
* Helm
* Kuttl
* Rust
* Python

The documentation is written in https://asciidoctor.org[AsciiDoc] format and processed with https://antora.org[Antora]

=== IDEs and Editors

Of course you are free to use whatever works for you best. No editor is perfect but we have positive experience with:

* `IntelliJ Idea` with the `Rust` plugin
* `VisualStudio Code` with the `rust-analyzer` plugin

For `VisualStudio Code` we also recommend the following plug-ins:
* Better Toml
* CodeLLDB (for debugging)
* Error Lens (inline error messages)
* AsciiDoc
* GitHub Pull requests and Issues
* GitLens
* Python
* Docker


