= Stackable Documentation
:page-layout: landing

Welcome to Stackable!
This documentation gives you an overview of the Stackable Data Platform, how to install and manage it as well as some tutorials.

++++
<br>
++++

++++
<div class="boxes two-column">
++++

++++
<div class="box">
++++

++++
<h3>Introduction</h3>
++++

If you have any feedback regarding the documentation please either open an https://github.com/stackabletech/documentation/issues[issue], ask a https://github.com/stackabletech/documentation/discussions[question] or look at the source for this documentation in its https://github.com/stackabletech/documentation[repository].

The Stackable Data Platform allows you to deploy, scale and manage Data infrastructure in any environment running https://kubernetes.io/[Kubernetes].

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Goal of the project</h3>
++++

We are building a distribution of existing Open Source tools that together comprise the components of a modern data platform.

There are components to ingest data, to store data, to process and visualize and much more.
While the platform got started in the _Big Data_ ecosystem we are in no way limited to big data workloads.

You can declaratively build these environments, and we don't stop at the tool level as we also provide ways for the users to interact with the platform in the "as Code"-approach.

We are leveraging the https://www.openpolicyagent.org/[Open Policy Agent] to provide Security-as-Code.

We are building a distribution that includes the “best of breed” of existing Open Source tools, but bundles them in a way, so it is easy to deploy a fully working stack of software. Most of the existing tools are “single purpose” tools, which often do not play nicely together out-of-the-box.

++++
</div>
++++

++++
</div>
++++

== Components

We are using Kubernetes as our deployment platform.
And we're building https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Operators] for each of the products we support.

The Stackable Data Platform supports the following products:

++++
<br>
++++

++++
<div class="boxes">
++++

++++
<div class="box">
++++

++++
<h3>Apache Airflow</h3>
++++

Airflow is a workflow engine and your replacement should you be using Apache Oozie.

link:/airflow/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache Druid</h3>
++++

Apache Druid is a real-time database to power modern analytics applications.

link:/druid/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache HBase</h3>
++++

HBase is a distributed, scalable, big data store

link:/hbase/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache Hadoop HDFS</h3>
++++

HDFS is a distributed file system that provides high-throughput access to application data.

link:/hdfs/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache Hive</h3>
++++

The Apache Hive data warehouse software facilitates reading, writing, and managing large datasets residing in distributed storage using SQL. We support the Hive Metastore.

link:/hive/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache Kafka</h3>
++++

Apache Kafka is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.

link:/kafka/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache NiFi</h3>
++++

An easy to use, powerful, and reliable system to process and distribute data.

link:/nifi/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache Spark</h3>
++++

Apache Spark is a multi-language engine for executing data engineering, data science, and machine learning on single-node machines or clusters.

link:/spark/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache Superset</h3>
++++

Apache Superset is a modern data exploration and visualization platform

link:/superset/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Trino</h3>
++++

Fast distributed SQL query engine for big data analytics that helps you explore your data universe.

link:/trino/index.html[Read more]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Apache ZooKeeper</h3>
++++

ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.

link:/zookeeper/index.html[Read more]

++++
</div>
++++


++++
</div>
++++
