= Stackable Documentation

Welcome to Stackable!
This documentation gives you an overview of our platform, how to install and manage it as well as some tutorials.

If you have any feedback regarding the documentation please either open an https://github.com/stackabletech/documentation/issues[issue], ask a https://github.com/stackabletech/documentation/discussions[question] or look at the source for this documentation in its https://github.com/stackabletech/documentation[repository].

== Introduction

Our Stackable platform allows you to deploy, scale and manage Big Data infrastructure in any environment as long as it can run https://kubernetes.io/[Kubernetes].

IMPORTANT: Our platform used to be based on a different architecture (until November 2021) where we built an alternative Kubelet. We abandoned that effort for now and are moving towards a Kubernetes-native experience using the normal `kubelet`.
This is an ongoing effort and the documentation might not reflect reality everywhere.
We aim to update our platform as well as the documentation by the end of 2021 and will remove this note when the migration has completed.

== Goal of the project

We are building a distribution of existing Open Source tools that together comprise the components of a modern data platform.

There are components to ingest data, to store data, to process and visualize and much more.
While the platform got started in the _Big Data_ ecosystem we are in no way limited to big data workloads.

You can declaratively build these environments, and we don't stop at the tool level as we also provide ways for the users to interact with the platform in the "as Code"-approach.

We are leveraging the https://www.openpolicyagent.org/[OpenPolicyAgent] to provide Authorization-as-Code.

We are building a distribution that includes the “best of breed” of existing Open Source tools, but bundles them in a way, so it is easy to deploy a fully working stack of software. Most of the existing tools are “single purpose” tools, which often do not play nicely together out-of-the-box.

== Components

We are using Kubernetes as our deployment platform.
And we're building https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Operators] for each of the products we support.

At the moment we support the following products (i.e. we have operators for each of those):

- https://druid.apache.org[Apache Druid]
- https://hbase.apache.org[Apache HBase]
- https://hadoop.apache.org[Apache Hadoop HDFS]
- https://hive.apache.org[Apache Hive Metastore]
- https://kafka.apache.org[Apache Kafka]
- https://nifi.apache.org[Apache NiFi]
- https://spark.apache.org[Apache Spark]
- https://superset.apache.org[Apache Superset]
- https://trino.io[Trino]
- https://zookeeper.apache.org[Apache ZooKeeper]

We are working on a feature matrix, so you can see which features we support for each of these products.

== Getting Started
Stackable provides a tutorial xref:getting_started.adoc[], which outlines how to deploy a Stackable cluster and the supported infrastructure. There is also a quickstart shell script in the https://github.com/stackabletech/stackable-utils[stackable-utils] GitHub repository that will quickly bootstrap an example cluster.
