= Stackable Documentation
:page-layout: landing

:k8s-operators: https://kubernetes.io/docs/concepts/extend-kubernetes/operator/
:docs-discussion: https://github.com/stackabletech/community/discussions
:docs-issues: https://github.com/stackabletech/documentation/issues
:docs-repo: https://github.com/stackabletech/documentation

++++
<style>
h1 {
    display: none; // hide the default title
}

.landing ul {
  list-style-type: none; /* Remove bullets */
  padding: 0; /* Remove padding */
  margin: 0; /* Remove margins */
}

#intro-action {
    margin-top: 5rem;
    margin-bottom: 2rem;
    font-size: 36px;
    text-align: center;
}

#help-action {
    margin-top: 3rem;
    margin-bottom: 1rem;
    font-size: 26px;
    text-align: center;
}

</style>
<div id="intro-action">What are you looking for?</div>
++++

++++
<div class="boxes">
++++

++++
<div class="box">
++++

++++
<h3>Getting started</h3>
++++

Get started with the Stackable Data Platform or a specific operator.

* xref:quickstart.adoc[]
* xref:tutorials:index.adoc#getting-started[Getting started per operator]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Demos and tutorials</h3>
++++

Run a demo data processing pipeline or follow a tutorial to learn about the platform hands-on.

* xref:demos:index.adoc[]
* xref:tutorials:index.adoc[]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Concept explanation</h3>
++++

Read concept explanation to gain a better understanding of how the Stackable Data platform works, 
or how a specific feature works.

xref:concepts:index.adoc[]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Product operator docs</h3>
++++

Read documentation for a specific product operator.
This includes a general overview, a getting started guide and specific feature usage guides.

xref:operators:index.adoc[Operator overview]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>CRD reference</h3>
++++

Read the CustomResourceDefinition (CRD) reference for all CRDs that are deployed by any Stackable operator.

https://crds.stackable.tech/[CRD Reference]

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Tooling</h3>
++++

Learn more about the tooling that supports the Stackable Data Platform; the `stackablectl` CLI utility and the Stackable Cockpit Web UI.

* xref:management:stackablectl:index.adoc[stackablectl]
* xref:management:cockpit:index.adoc[Cockpit UI]

++++
</div>
++++

++++
</div>
++++

++++
<div id="help-action">Still need help? Ask a question on <a href="https://github.com/orgs/stackabletech/discussions">GitHub</a> or <a href="https://discord.com/invite/7kZ3BNnCAF">Discord</a>.</div>
++++
