= Stackable Documentation
:page-layout: landing

:k8s-operators: https://kubernetes.io/docs/concepts/extend-kubernetes/operator/
:docs-discussion: https://github.com/stackabletech/community/discussions
:docs-issues: https://github.com/stackabletech/documentation/issues
:docs-repo: https://github.com/stackabletech/documentation

Welcome to Stackable!
This documentation gives you an overview of the Stackable Data Platform, how to install and manage it as well as some
tutorials.

++++
<div class="boxes two-column">
++++

++++
<div class="box">
++++

++++
<h3>Introduction</h3>
++++

The Stackable Data Platform allows you to deploy, scale and manage Data infrastructure in any environment running
https://kubernetes.io/[Kubernetes].

You can find an overview of the supported components <<Components,below>>, as well as a full list of all supported
product versions xref:operators:supported_versions.adoc[here].

If you have any feedback regarding the documentation please either open an {docs-issues}[issue], ask a
{docs-discussion}[question] or look at the source for this documentation in its {docs-repo}[repository].

++++
</div>
++++

++++
<div class="box">
++++

++++
<h3>Goal of the project</h3>
++++

We are building a distribution of existing Open Source tools that together comprise the components of a modern data
platform.

There are components to ingest data, to store data, to process and visualize and much more. While the platform got
started in the _Big Data_ ecosystem we are in no way limited to big data workloads.

You can declaratively build these environments, and we don't stop at the tool level as we also provide ways for the
users to interact with the platform in the "as Code"-approach.

We are leveraging the https://www.openpolicyagent.org/[Open Policy Agent] to provide Security-as-Code.

We are building a distribution that includes the “best of breed” of existing Open Source tools, but bundles them in a
way, so it is easy to deploy a fully working stack of software. Most of the existing tools are “single purpose” tools,
which often do not play nicely together out-of-the-box.

++++
</div>
++++

++++
</div>
++++

== Release Notes

The Stackable platform consists of multiple operators that work together. Periodically a platform release is made,
including all components of the platform at a specific version. See the latest release notes for 23.7
xref:release_notes.adoc[here].
