= Default Paths

This page documents the filesystem paths our components use by default.

Configuration (`/etc/stackable`)::
Most of the Stackable products are not configured via config files but if they are you'll find their configuration in subdirectories here. One example is the agent which has its configuration at `/etc/stackable/agent`.

Service Configuration (`/etc/stackable/serviceconfig`)::
This directory contains the _materialized_ configuration for each instance of a product that is being executed by our agent.

This means that every (e.g.) restart of a product, or each configuration change will result in a new subdirectory in this directory. This new subdirectory will include the full configuration used by this _run_ of a product.

Binaries (`/opt/stackable/<name>`)::
There will be a subdirectory under `/opt/stackable` for each of our operators as well as the agent (e.g. `/opt/stackable/agent`) which contains the binaries of these products.

Packages (`/opt/stackable/packages`)::
This directory contains all our downloaded and expanded packages.
Packages are the downloaded end products (e.g. Apache NiFi).

Logs (`/var/log/stackable/servicelogs/<name>`)::
This is the default location for logs for the services you deploy (e.g. the Apache Kafka broker logs).
