= Product information

This page contains contrete specifications about the Stackable Data Platform (SDP) as a product, which components are included, how they are supplied and which external dependencies exist that you as a customer need to take care of.

== Platform components

The Stackable Platform is made up of multiple components. Operators for data products, Operators for additional functionality to facilitate easy integration between the different products. Auxilary software to interact with the platform, as well as software to ease the deployment of platform components.

=== Kubernetes Operators

The main components of the SDP are Kubernetes Operators. Each Operator is supplied in a Docker <<containers, container>> image. For every Operator there is also a Helm Chart to facilitate installation via Helm. Operators for Products supported by the Platform deploy these products as <<containers, containers>> in Kubernetes.

Supported products:

* xref:airflow:index.adoc[Apache Airflow]
* xref:druid:index.adoc[Apache Druid]
* xref:hbase:index.adoc[Apache HBase] (including xref:hbase:usage-guide/phoenix.adoc[Apache Phoenix])
* xref:hive:index.adoc[Apache Hive Metastore]
* xref:hdfs:index.adoc[Apache Hadoop HDFS]
* xref:kafka:index.adoc[Apache Kafka]
* xref:nifi:index.adoc[Apache Nifi]
* xref:spark-k8s:index.adoc[Apache Spark] (including xref:spark-k8s:usage-guide/history-server.adoc[Spark History Server])
* xref:superset:index.adoc[Apache Superset]
* xref:trino:index.adoc[Trino]
* xref:zookeeper:index.adoc[Apache Zookeeper]
* xref:opa:index.adoc[Open Policy Agent]

Refer to the xref:operators:supported_versions.adoc[list of supported product versions] to find out which product versions are supported.

The product also includes the xref:commons-operator:index.adoc[Commons], xref:secret-operator:index.adoc[Secret] and xref:listener-operator:index.adoc[Listener] Operators.

[#stackablectl]
=== stackablectl

xref:stackablectl::index.adoc[stackablectl] is a commandline utility that makes it easier to install and interact with stackable components.

== Supported installation methods

[#containers]
=== Operators and products

All operators are supplied in container images. The products are also deployed in container images.
The docker images can be found here: https://repo.stackable.tech/#browse/browse:docker

Stackable supports installing the Operators via https://helm.sh/[Helm] or with <<stackablectl>>.
Every Operator includes installation instructions in the Getting started guide.

==== Helm Charts

The Helm Charts can be found here: https://repo.stackable.tech/#browse/browse:helm-stable


[#stackablectl-installation]
=== stackablectl

stackablectl is available for download, pre-built binaries are available on GitHub. The download link and installation steps are provided in the xref:stackablectl::installation.adoc[installation documentation].

== System requirements

=== Operators

Every Operator needs:

* 0.2 cores (i.e. i5 or similar)
* 256MB RAM

=== stackablectl

Hardware requirements and supported operating systems can be found in the xref:stackablectl::installation.adoc#system-requirements[system requirements section] of the stackablectl documentation.

=== Stackable Data Platform Open Source Products

The system requirements of each open source product depend on usage.

== Prerequisites and required external components

Required external components are components that are required for the platform or parts of it to operate, but are not part of the Stackable Data Platform. Note that Stackable does not offer support for the external components.

=== Kubernetes

A Kubernetes cluster is required to install the Stackable Data Platform. The following Kubernetes distributions are supported:

include::partial$supported-kubernetes-distributions.adoc[]

=== Product specific dependencies

The following products have required external components to run:

* xref:airflow:required-external-components.adoc[Apache Airflow]
* xref:druid:required-external-components.adoc[Apache Druid]
* xref:hive:required-external-components.adoc[Apache Hive]
* xref:superset:required-external-components.adoc[Apache Superset]
