= Quickstart

:cockpit-releases: https://github.com/stackabletech/stackable-cockpit/releases

This is the super-short getting started guide that should enable you to get something up and running in less than three
minutes (excluding download times).

== Setup

Install `stackablectl`, the Stackable CLI utility.

On Linux (Windows and MacOS instructions below):

[source,console]
----
$ curl -L -o stackablectl https://github.com/stackabletech/stackable-cockpit/releases/latest/download/stackablectl-x86_64-unknown-linux-gnu
----

and mark it as executable:

[source,console]
----
$ chmod +x stackablectl
----

.Instruction for Windows and MacOS
[%collapsible]
====
Download `stackablectl-x86_64-pc-windows-gnu.exe` (for Windows) or `stackablectl-x86_64-apple-darwin` (Mac OS Intel) or
`stackablectl-aarch64-apple-darwin` (MacOS ARM) from the {cockpit-releases}[latest release] and save it as
`stackablectl`. For Windows, you can simply execute it. For MacOS mark it as executable:

[source,console]
----
$ chmod +x stackablectl
----

If you want to execute it from anywhere in your system, you need to add it to the system `PATH`.

NOTE: If macOS denies the execution of stackablectl go to `Settings` -> `Security & Privacy` -> `General`. Here you will
see a pop up asking if you want to allow access for `stackablectl`. You must allow access.
====

== Install the Taxi data demo

The xref:demos::trino-taxi-data.adoc[`trino-taxi-data`] Demo installs the latest Stackable platform release and a
visualization of https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page[New York City Taxi Data] using Trino and
Superset:

[source,console]
----
./stackablectl demo install trino-taxi-data
----

TIP: Learn more about this demo in the demo docs: xref:demos::trino-taxi-data.adoc[]

== Connect

To list the installed installed Stackable services run the following command:

[source,console]
----
./stackablectl services list --all-namespaces
----

It will output something like:

[source]
----
 PRODUCT   NAME         NAMESPACE  ENDPOINTS                                     EXTRA INFOS                          
                                                                                                                      
 hive      hive         default    hive                172.18.0.5:30298                                               
                                   metrics             172.18.0.5:31633                                               
                                                                                                                      
 opa       opa          default    http                http://172.18.0.5:30316                                        
                                                                                                                      
 superset  superset     default    external-superset   http://172.18.0.4:32295   Admin user: admin, password: adminadmin   
                                                                                                                      
 trino     trino        default    coordinator-http    http://172.18.0.3:30167                                        
                                   coordinator-metrics 172.18.0.3:31818                                               
                                   coordinator-https   https://172.18.0.3:30141                                       
                                                                                                                      
 minio     minio-trino  default    http                http://172.18.0.3:31062   Third party service                  
                                   console-http        http://172.18.0.3:30503   Admin user: admin, password: adminadmin
----

To connect to Superset, open the listed endpoint in your browser and log in with the username `admin` and the password
`adminadmin`.
