= Quickstart

:latest-release: https://github.com/stackabletech/stackable-cockpit/releases/tag/stackablectl-1.0.0-rc1
:cockpit-releases: https://github.com/stackabletech/stackable-cockpit/releases

This is the super-short getting started guide that should enable you to get something up and running in less than three
minutes (excluding download times).

== Setup

Install `stackablectl`, the Stackable CLI utility.

=== Installation on Linux

Download the `stackablectl-x86_64-unknown-linux-gnu` binary file from the link:{latest-release}[latest release], then
rename the file to `stackablectl`. You can also use the following command:

[source,console]
----
wget -O stackablectl https://github.com/stackabletech/stackable-cockpit/releases/download/stackablectl-1.0.0-rc1/stackablectl-x86_64-unknown-linux-gnu
# or
curl -L -o stackablectl https://github.com/stackabletech/stackable-cockpit/releases/download/stackablectl-1.0.0-rc1/stackablectl-x86_64-unknown-linux-gnu
----

Mark the binary as executable:

[source,console]
----
chmod +x stackablectl
----

Then, make sure it is present in your `$PATH`, like `/usr/local/bin`.

=== Installation on macOS and Windows

See the xref:management:stackablectl:installation.adoc[guide] for detailed information about the installation process on macOS and Windows.

== Install the Taxi data demo

The xref:demos:trino-taxi-data.adoc[`trino-taxi-data`] Demo installs the latest Stackable platform release and a
visualization of https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page[New York City Taxi Data] using Trino and
Superset:

[source,console]
----
./stackablectl demo install trino-taxi-data
----

TIP: Learn more about this demo in the demo docs: xref:demos:trino-taxi-data.adoc[]

== Connect

To list the installed installed Stackable services run the following command:

[source,console]
----
./stackablectl stacklet list
----

It will output something like:

[source]
----
 PRODUCT   NAME         NAMESPACE  ENDPOINTS                                  
                                                                              
 hive      hive         default    hive                172.18.0.5:30298       
                                   metrics             172.18.0.5:31633       
                                                                              
 opa       opa          default    http                http://172.18.0.5:30316
                                                                              
 superset  superset     default    external-superset   http://172.18.0.4:32295
                                                                              
 trino     trino        default    coordinator-http    http://172.18.0.3:30167
                                   coordinator-metrics 172.18.0.3:31818       
                                   coordinator-https   https://172.18.0.3:3014
                                                                              
 minio     minio-trino  default    http                http://172.18.0.3:31062
                                   console-http        http://172.18.0.3:30503
----

To connect to Superset, open the listed endpoint in your browser and log in with the username `admin` and the password
`adminadmin`. Use the `stackablectl stacklet credentials` command to retrieve credentials for various stacklets.
