= Releases

The Stackable platform consists of multiple operators that work together. Periodically a platform release is made, including all components of the platform at a specific version. The goal of the platform is to support the last three stable versions of each product.

== Release 22.06

This is the first release of the platform, bringing operators for 12 products as well as <<_stackablectl>>, the commandline tool to easily install data products in Kubernetes. Operators spin up production ready product applications. Also there are some common features across all operators, such as monitoring, service discovery and configuration overrides. Find the <<Platform features>>, <<_stackablectl,stackablectl features>> and <<_operators>> below.

=== Platform features

==== Easily install production ready data applications

All operators spin up production ready product instances.

==== Monitoring

All products have monitoring with prometheus enabled.
//
xref:operators:monitoring.adoc[Learn more]

==== Service discovery

Products on the Stackable platform use service discovery to easily interconnect with each other.
//
xref:concepts:service_discovery.adoc[Learn more]

==== Configuration overrides

All operators support configuration overrides, these are documented in the specific operator documentation pages.

==== Common S3 configuration

Many products support connecting to S3 to load and/or store data. There is a common resource for S3 connections and buckets across all operators that can be reused.
//
xref:concepts:s3.adoc[Learn more]

==== Roles and role groups

Most products consist of multiple processes. All operators support configuring processes individually.

=== stackablectl

stackablectl is used to install and interact with the operators, either individually or multiple at once.
//
xref:stackablectl::index.adoc[Learn more]

=== Operators

This is the list of all operators in this current release, with their versions for this release.

* xref:airflow::index.adoc[]
** Load DAGs from ConfigMaps or PersistentVolumeClaims
* xref:druid::index.adoc[]
** S3 and HDFS as deep storage options
** ingestion from S3 buckets
** authorization using OPA
* xref:hbase::index.adoc[]
* xref:hdfs::index.adoc[]
* xref:hive::index.adoc[]
** Hive Metastore can index S3
* xref:kafka::index.adoc[]
** Seamless integration with NiFi and Druid
** Supports OPA authorization
* xref:nifi::index.adoc[]
* xref:spark-k8s::index.adoc[]
* xref:superset::index.adoc[]
** connects to Druid as a backend
* xref:trino::index.adoc[]
** Supports OPA and file-based authorization
** Connects to the Hive Metastore
** Query data from S3
** TLS support
* xref:zookeeper::index.adoc[]
** Supports creating ZNodes with CRDs
* xref:opa::index.adoc[]
** Create RegoRules in ConfigMaps
* xref:commons-operator::index.adoc[]
* xref:secret-operator::index.adoc[]
