---
extends: default

rules:
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1  # Needed due to https://github.com/adrienverge/yamllint/issues/443
  document-start:
    ignore:
    - modules/**/examples/**  # We don't want the `---` in doc includes.
  indentation:
    indent-sequences: consistent
