[build]
  command = "make netlify-build"
  publish = "build/site"

# Rate limiting across the whole page. 250 request per 60 seconds aggregated by client IP.
[[redirects]]
  from = "/*"
  to = "/:splat"
    [redirects.rate_limit]
    window_limit = 250
    window_size = 60
    aggregate_by = ["ip"]

[[redirects]]
  from = "/home/stable/reference/*"
  to = "https://hub.stackable.tech/crds"
  status = 301

[[redirects]]
  from = "/home/stable/release_notes.html"
  to = "/home/stable/release-notes"
  status = 301
