[build]
  command = "make netlify-build"
  publish = "build/site"

[[redirects]]
  from = "/home/stable/reference/*"
  to = "https://crds.stackable.tech/"
  status = 301

[[redirects]]
  from = "/home/stable/release_notes.html"
  to = "/home/stable/release-notes"
  status = 301
