---
site:
  title: Stackable Documentation
  url: https://docs.stackable.tech
  start_page: home::index.adoc
  robots: allow
  keys:
    enable_tracking: false
urls:
  # This replaces the component version in the URL of the latest stable version with 'stable'
  # i.e. /commons-operator/stable/index.html instead of /commons-operator/0.3/index.html
  latest_version_segment: stable
content:
  sources:
    - url: ./
      branches:
        - HEAD
    # management tools
    - url: https://github.com/stackabletech/stackable-cockpit.git
      start_path: docs
      branches: main
    # demos
    - url: https://github.com/stackabletech/demos.git
      start_path: docs
      branches:
        - main
    # internal operators
    - url: https://github.com/stackabletech/commons-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/secret-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/listener-operator.git
      start_path: docs
      branches:
        - main
    # product operators
    - url: https://github.com/stackabletech/airflow-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/druid-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/hbase-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/hdfs-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/hive-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/kafka-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/nifi-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/opa-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/spark-k8s-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/superset-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/trino-operator.git
      start_path: docs
      branches:
        - main
    - url: https://github.com/stackabletech/zookeeper-operator.git
      start_path: docs
      branches:
        - main
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    base-repo: https://github.com/stackabletech
    plantuml-server-url: http://www.plantuml.com/plantuml
    kroki-fetch-diagram: true
    # an external icon. Create a link opening in a new tab like this: http://my-url.com[Text {external-link-icon}^]
    external-link-icon: "<i class=\"fa-solid fa-arrow-up-right-from-square fa-xs\" style=\"margin-left: 3px; vertical-align: baseline;\"></i>"
# the default caching directory is ./.cache/antora
# Antora caches the git repos, this can sometimes lead to stale content
# use 'make clean' to remove the build and cache directory
runtime:
  cache_dir: ./cache
  log:
    failure_level: warn
