// Header of this document:
//

= Stackable Documentation
:base-repo: https://github.com/stackabletech

This is the main repository for the documentation of the Stackable platform.
Have a look at the https://docs.stackable.tech/[live version].

The documentation is built with https://antora.org[Antora]. This repository hosts the Antora playbook file as well as platform documentation. Other Stackable repos contain 'docs' directories which are pulled in by this repo.

To build the site, pull submodules, install dependencies and run `make`:

[source,console]
----
$ git submodule update --init
$ npm ci
$ make
----

NOTE: Antora caches the external content repos in the cache directory (configured to be `./cache`). It will _not_ automatically update those.  Use the `--fetch` flag (`make ANTORAFLAGS=--fetch`) to update all sources, or use `make clean` to delete the `cache` and `build` directory.

== Development

=== Generating the documentation

During development, it can be helpful to use a playbook `local-antora-playbook.yml` which uses content from the local directory instead of the remote git repository. The playbook used by the `Makefile` can be overridden using the `PLAYBOOK` variable (run `make PLAYBOOK=my-local-playbook.yml`).

[source,yaml]
----
content:
  sources:
  - url: ./
    branches: HEAD
----

NOTE: Antora does not recognize git submodules as git repositories

The design & layout comes from our https://github.com/stackabletech/documentation-ui[UI repository].

`LIVERELOAD=true gulp` may be used to recreate the built documentation after each edit. The 'live reload' feature does not work over gitpod currently due to https://github.com/schickling/gulp-webserver/pull/126

=== Remote IDE

A remote vscode instance can be used via https://gitpod.io/#/github.com/stackabletech/documentation

== Tracking

The documentation UI includes a script for user tracking. The documentation can be built with or without it. Tracking enabled/disabled by setting `site.keys.enable_tracking` to `true` or `false`. The tracking code is in the UI repository in `src/partials/head-scripts.hbs`.
