// Header of this document:

= Stackable Documentation
:base-repo: https://github.com/stackabletech

This is the main repository for the documentation of the Stackable platform.
It uses https://antora.org[Antora].

This repository hosts the Antora playbook file as well as some generic documentation modules.

To build the site, pull submodules, install dependencies and run `make`:

[source,console]
----
$ git submodule update --init
$ npm ci
$ make
----

NOTE: Antora caches all resources it downloads in the user's cache directory (e.g. `~/.cache/antora` directory on Linux). It will _not_ automatically update those. Use the `--fetch` flag (`make ANTORAFLAGS=--fetch`) to update all sources.

== Development

=== Generating the documentation

During development, it can be helpful to use a playbook `local-antora-playbook.yml` which uses content from the local directory instead of the remote git repository. The playbook used by the `Makefile` can be overridden using the `PLAYBOOK` variable (run `make PLAYBOOK=my-local-playbook.yml`).

[source,yaml]
----
content:
  sources:
  - url: ./
    branches: HEAD
----

NOTE: Antora does not recognize git submodules as git repositories

The design & layout comes from our https://github.com/stackabletech/documentation-ui[UI repository].

`LIVERELOAD=true gulp` may be used to recreate the built documentation after each edit. The 'live reload' feature does not work over gitpod currently due to https://github.com/schickling/gulp-webserver/pull/126

=== Remote IDE

A remote vscode instance can be used via https://gitpod.io/#/github.com/stackabletech/documentation
