// Header of this document:

= Stackable Documentation
:base-repo: https://github.com/stackabletech

This is the main repository for the documentation of the Stackable platform.
It uses https://antora.org[Antora].

This repository hosts the Antora playbook file as well as some generic documentation modules.

To build the site install Antora and run:

    antora antora-playbook.yml

NOTE: Antora caches all resources it downloads in the user's cache directory (e.g. `~/.cache/antora` directory on Linux). It will _not_ automatically update those. Use the `--fetch` parameter to update all sources.

== Development

=== Generating the documentation

During development, it can be helpful to use a playbook `local-antora-playbook.yml` which uses content from the local directory instead of the remote git repository.

[source,yaml]
----
content:
  sources:
  - url: ./
    branches: HEAD
----

NOTE: Antora does not recognize git submodules as git repositories

The design & layout comes from our https://github.com/stackabletech/documentation-ui[UI repository].

`LIVERELOAD=true gulp` may be used to recreate the built documentation after each edit. The 'live reload' feature does not work over gitpod currently due to https://github.com/schickling/gulp-webserver/pull/126

=== Remote IDE

A remote vscode instance can be used via https://gitpod.io/#/github.com/stackabletech/documentation

=== Generate the documentation with a Docker utility container

This method has the advantage that you don't need a local installation of Antora. The image `docker.stackable.tech/stackable/antora:3.0.1-stackable0` comes bundled with the required https://gitlab.com/antora/antora-lunr-extension[lunr] extension.

[source,yaml]
----
docker run -u $(id -u) -v $PWD:/antora:Z -w /antora --rm -t docker.stackable.tech/stackable/antora:3.0.1-stackable0 docker-antora-playbook.yml
----

