// Header of this document:

= Stackable Documentation
:base-repo: https://github.com/stackabletech

This is the main repository for the documentation of the Stackable platform.
It uses https://antora.org[Antora].

This repository hosts the Antora playbook file as well as some generic documentation modules.

To build the site install Antora and run:

    antora antora-playbook.yml

WARNING: Due to a https://gitlab.com/antora/antora/-/issues/745[bug] this will _not_ currently work in Node 16. I recommend using the latest LTS release (14) until the issue is resolved.

== Development

=== Generating the documentation

During development, it can be helpful to use a playbook `antora-playbook-local.yml` which uses content from the local directory instead of remote git repository.

NOTE: Antora does not recognize git submodules as git repositories

The design & layout comes from our https://github.com/stackabletech/documentation-ui[UI repository].

`LIVERELOAD=true gulp` may be used to recreate the built documentation after each edit. The 'live reload' feature does not work over gitpod currently due to https://github.com/schickling/gulp-webserver/pull/126

=== Remote IDE

A remote vscode instance can be used via https://gitpod.io/#/github.com/stackabletech/documentation

