---
site:
  title: Stackable Documentation
  url: https://docs.stackable.tech
  start_page: home::index.adoc
  robots: allow
  keys:
    enable_tracking: false
urls:
  # This replaces the component version in the URL of the latest stable version with 'stable'
  # i.e. /commons-operator/stable/index.html instead of /commons-operator/0.3/index.html
  latest_version_segment: stable
content:
  sources:
    - url: ./
      branches:
        - HEAD
    # management tools
    - url: ../stackable-cockpit/
      start_path: docs
    # demos
    - url: ../demos/
      start_path: docs
    # internal operators
    - url: ../commons-operator/
      start_path: docs
    - url: ../secret-operator/
      start_path: docs
    - url: ../listener-operator/
      start_path: docs
    # product operators
    - url: ../airflow-operator/
      start_path: docs
    - url: ../druid-operator/
      start_path: docs
    - url: ../hbase-operator/
      start_path: docs
    - url: ../hdfs-operator/
      start_path: docs
    - url: ../hive-operator/
      start_path: docs
    - url: ../kafka-operator/
      start_path: docs
    - url: ../nifi-operator/
      start_path: docs
    - url: ../opa-operator/
      start_path: docs
    - url: ../opensearch-operator/
      start_path: docs
    - url: ../spark-k8s-operator/
      start_path: docs
    - url: ../superset-operator/
      start_path: docs
    - url: ../trino-operator/
      start_path: docs
    - url: ../zookeeper-operator/
      start_path: docs
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
    - asciidoctor-kroki
  attributes:
    base-repo: https://github.com/stackabletech
    plantuml-server-url: http://www.plantuml.com/plantuml
    kroki-fetch-diagram: true
    # an external icon. Create a link opening in a new tab like this: http://my-url.com[Text {external-link-icon}^]
    external-link-icon: "<i class=\"fa-solid fa-arrow-up-right-from-square fa-xs\" style=\"margin-left: 3px; vertical-align: baseline;\"></i>"
# the default caching directory is ./.cache/antora
# Antora caches the git repos, this can sometimes lead to stale content
# use 'make clean' to remove the build and cache directory
runtime:
  cache_dir: ./cache
  log:
    failure_level: warn
