= Maturity Level 1
Jim Halfpenny <jim@source321.com>
v1.0, 04.05.2021
:status: draft
:toc:
:icons: font

*Status*: {status}

== Objective
The aim for maturity level 1 is to provide an MVP of Stackable, including delivery of the essential components needed to deploy the initial service offerings. This will serve to deliver the essential components that form the foundation of Stackable, including the agent and operators.

A strong part of this foundation is the principle of infrastructure as code to define services and their relationships. By working with code from the ground up Stackable will provide a means to manage, revise and control service configuration. This will allow for repeatable deployments, easier integration with devops tools and better control over the platform lifecycle in comparison to other products.

== Features
=== Services
A core list of initially supported services for which Stackable operators have been written will be available. The service configuration provided will be enough to get the services deployed, running and working with the other components. A completed service operator for must implement start, stop and restart for its respective service. This is the baseline for acceptance of new operators into the stack.

The initially supported components will have the supported versions documented i.e. those that have been tested individually and as part of the wider stack. Compatible versions may be listed as either a specific version, or a range of versions. The initial list of core services are expected to include:

* https://hadoop.apache.org/[Apache Hadoop HDFS]
* https://hadoop.apache.org/[Apache Hadoop YARN]
* https://kafka.apache.org/[Apache Kafka]
* https://nifi.apache.org/[Apache NiFi]
* https://spark.apache.org/[Apache Spark]
* https://zookeeper.apache.org/[Apache Zookeeper]

=== Installation and Upgrades
Stackable will be provided as a software package and installation of Stackable will via be a documented manual process. This may involve the installation of OS software packages and manual configuration. Some prerequisites may be added using the OS package manager, but some dependencies will need to be satisfied manually.

Support for minor version upgrades for components requiring a full cluster stop will be available.

=== Automated Provisioning
Stackable will be able to deploy and configure a service for a given specification presented as a YAML file. It will be able to link a service with its dependencies e.g. associating a Kafka deployment with its Zookeeper service. Services once deployed can also be shut down and destroyed.

=== Configuration management
Configuration of Stackable components will be via a manually-created YAML file. Examples of valid service files will be made available by Stackable to serve as templates for customer deployments. Basic configuration validation such as ensuring that mandatory configuration values are included and type checking of values will be performed.

Once a service is deployed changes can be made to its configuration and then pushed out to the cluster, restarting the services as required. No support for rolling restarts at this stage.

=== Security and  Governance
Authentication for many data platforms uses Kerberos. MIT Kerberos operator.

Stackable introduces at this maturity level a managed security framework using https://www.openpolicyagent.org/[Open Policy Agent (OPA)]. The aim is to use OPA as the authorisation framework for all the Stackable operators and promote the security as code model for access control. Integration for OPA already exists for Kafka, which will serve as a demonstration for OPA for managed authorisation. Securing other services that don't currently have OPA integration will be limited to what can be placed into the operator service configuration. Where supported, security policy and ACLs can be applied manually.

Wire encryption can be enabled manually with the end user being responsible for distribution of cryptographic keys and certificates.

== Use Cases
=== Demo Application

Stackable will ship with at least one example application. This will provide a walkthrough tutorial demonstrating how to install Stackable, deploy services and run the demo application. The goal is to provide a hands-on way to  A technologically able user should be able to follow the documentation to deploy Stackable and to run an example application on the Stack.

=== User Stories
Stackable will deliver the ability to deploy a data platform with sufficient breadth to allow data storage, movement and processing.

* "As a data custodian I'd like to create a Stackable data lake to store and process our high-volume business data."
* "As a Data Scientist I'd like to calculate a Page Rank with SparklyR from RStudio on a stackable powered Spark cluster."
* "As a specialist field / department I’d like to securely ingest a data stream into a stackable powered Kafka cluster"


