= Maturity Level 2
Jim Halfpenny <jim@source321.com>
v1.0, 04.05.2021
:status: draft
:toc:
:icons: font

*Status*: {status}

== Objective
The aim for maturity level 2 is to build on the core foundation of the Stackable platform and ready it for its GA release. This will include the introduction of new components to Stackable as well as improving the installation process and overall usability. Priority will be given to new components that round out the capabilities of the platform and ensure a broad range of functionality.

== Features
=== Services
New operators will be added to the stack, with priority given to those that complete the stack. The aim is to provide a comprehensive range of components to cover as wide a range of use cases as possible including storage, data processing, query engines and visualisation.

Services will be able to be associated with one another to satisfy dependencies and to provide client configuration for services that require it. For example a Spark service can be associated with a HDFS service to provide the configuration to allow file access.

=== Installation and Upgrades
A more polished installation experience will be introduced, making it easier to install with the majority of software dependencies being met automatically.

An upgrade path from previous versions of Stackable will become available. This includes upgrading stackable operators with the option to rollback to the previous version.


=== Automated Provisioning
Template based deployment of a stack. You should be able to define what services you need and have them deployed, with mutual configuration carried out to link the services.


=== Configuration management
There will be improvements to configuration validation with the introduction of validity checks e.g. is a configuration parameter within acceptable bounds.

Best practice

=== Security and Governance
At this maturity level a managed security framework will be introduced, using the https://www.openpolicyagent.org/[Open Policy Agent (OPA)]

==== Authentication
Kerberos authenitcation is available on most of the components. This is not ideal for end user interactions, fine for server to server. Is there a way to unify the authentication protocols? One protocol ideally?

==== Authorisation
===== Integration with OPA
* Which services support OPA?
* What can we make work with OPA?

=== Accounting/Audit
* Can we also use OPA for audit? How and where?
** Do we use OPA to audit based on access? We'd need to send every request to OPA, how does this work with policy caching?
** Local audit from each service? (This is what Ranger does)

=== Demo Applications
Provide a tutorial/demo that uses as much of the stack as possible. It should mimic some sort of real world application and possible serve as a template.

* What should this be?
** IoT
** Data warehouse

Start to build a collection of example use cases.

