= Maturity Level 2
Jim Halfpenny <jim@source321.com>
v1.0, 04.05.2021
:status: draft
:toc:
:icons: font

*Status*: {status}

== Objective
The aim for maturity level 2 is to build on the core product and ready it for GA release. This will include the introduction of new components to Stackable as well as improving the installation process and overall usability. Priority will be given to new components that round out the stack and improve the capabilities of the platform.


== Services
New operators will be added to the stack, with priority given to those that complete the stack. The aim is to provide a comprehensive range of components to cover as wide a range of use cases as possible. Storage, execution framework, visualisation.

=== Proposed list of services to be added
* https://hadoop.apache.org/[Apache Hadoop (HDFS, YARN, MapReduce)]
* https://druid.apache.org/[Apache Druid]
* https://superset.apache.org/[Apache Superset]
* https://trino.io/[Trino]
* https://airflow.apache.org/[Apache Airflow]
* https://iotdb.apache.org/[Apache IoTDB]


== Installation and Upgrades

* Test upgrades for new components.
* Support rolling upgrades where possible.


=== Automated Provisioning
Template based deployment of a stack. You should be able to define what services you need and have them deployed, with mutual configuration carried out to link the services.


=== Configuration management
Improved validation



== Security and Governance
=== Authentication
Kerberos authenitcation is available on most of the components. This is not ideal for end user interactions, fine for server to server. Is there a way to unify the authentication protocols? One protocol ideally?

=== Authorisation
==== Integration with OPA
* Which services support OPA?
* What can we make work with OPA?

=== Accounting/Audit
* Can we also use OPA for audit? How and where?
** Do we use OPA to audit based on access? We'd need to send every request to OPA, how does this work with policy caching?
** Local audit from each service? (This is what Ranger does)

=== Demo Applications
Provide a tutorial/demo that uses as much of the stack as possible. It should mimic some sort of real world application and possible serve as a template.

* What should this be?
** IoT
** Data warehouse

Start to build a collection of example use cases.

