= Maturity Level 3
Jim Halfpenny <jim@source321.com>
v1.0, 04.05.2021
:status: draft
:toc:
:icons: font

*Status*: {status}

== Objective
The aim for maturity level 3 is to provide a platform fit for GA release. This means having a comprehensive set of operators, a robust deployment and management framework and comprehensive product documentation. Installation at this stage will be largely automated with a comprehensive installation guide.

This milestone will see the introduction and release of a functional control plane user interface for deployment and management of Stackable.


== Services
The core operators will have already been delivered and effort will instead be made into ensuring their robustness. A library of service templates will be provided to make deployment of common use cases straightforward and act as the bases for bespoke deployments.

New operators added to Stackable based on priority, maturity and user feedback. Integration of these services with 3rd party partner tools and services will also be documented at this stage, allowing Stackable to integrate better with other data-centric tooling used by customers.


== Installation and Upgrades
Installation of Stackable itself will be mature and well automated at this stage. Stackable will also have a documented migration path away from other big data platforms, providing a roadmap for customers wishing to move to Stackable. This will suit self supporters, customer looking to unify disparate products and those wishing to migrate away from proprietary alternatives.

Upgrade between major versions. Including updates to schemas and file formats where needed. Rollback based on point in time snapshot of pre-upgrade environment.

=== Automated Provisioning
Stackable will have greater control over the platforms it can be deployed to, with support public cloud vendors, Kubernetes, bare metal and hybrid deployments. There will be an API for publishing service templates to create a fully working cluster. Validation will be improved so that configuration errors are picked up early and fixed prior to deployment.

The control plane will offer a wizard based deployment, allowing customer to choose the services they would like to deploy, where they will be deployed and highlight any missing service dependencies.

=== Configuration management
The control plane will provide an interactive way to view and change service configuration and to push these changes out to the running services. Broad range of configuration options will be made available and documented for each service. The expertise of Stackable will allow for richer health checks/sanity checks/configuration validation.

=== Security and Governance
Stackable will be able to provide guided installation of services that can be secured with the minimum of manual intervention and adherence to best practice. The most commonly available security features can be enabled when services are deployed.

The control plane will evaluate and report on the security posture of deployed services and offer suggestions on how to improve security. Missing or unconfigured security features will be highlighted with a remedy offered to address the issue.

Stackable will provide bulletins warning of new security issues and remediation steps including patches. These bulletins will be published on the web, delivered by email and published to a feed that can be read into the UI to provide operators with the information directly.

== Use Cases
=== Demo Applications
A library of fully working demos to show off the capabilities of Stackable. These will cover a number of use cases in different verticals and act as demonstrations of Stackable capabilities.

* Platform deployment demo for operators
* Demo applications and use cases
** Streaming
** Machine Learning
** Data visualisation
** Big data analysis
** Big data query