= Maturity Level 3
Jim Halfpenny <jim@source321.com>
v1.0, 04.05.2021
:status: draft
:toc:
:icons: font

*Status*: {status}

== Objective
The aim for maturity level 3 is to provide a platform fit for GA release. This means having a comprehensive set of operators, a robust deployment and management framework and comprehensive product documentation. Installation at this stage will be largely automated with a comprehensive installation guide.

This milestone will see the introduction and release of a functional user interface for deployment and management of Stackable.


== Services
The core operators will have already been delivered and effort will instead be made into ensuring their robustness. A library of service templates will be provided to make deployment of common use cases straightforward and act as the bases for bespoke deployments.

New operators added to Stackable based on priority, maturity and user feedback. Integration of these services with 3rd party partner tools and services will also be documented at this stage, allowing Stackable to integrate better with other data-centric tooling used by customers.


== Installation and Upgrades
Installation of Stackable itself will be mature and well automated at this stage. Stackable will also have a documented migration path away from other big data platforms, allowing in-situ migration and adoption of existing deployments as well as a roadmap for moving to Stackable. This will suit self supporters, customer looking to unify disparate products and those wishing to migrate away from proprietary alternatives.


=== Automated Provisioning
Greater control over the platforms Stackable can be deployed to. Cloud vendors, Kubernetes, bare metal, hybrid.

API for pushing templates to create a fully working cluster. Validation so that configuration errors, missing or incompatible dependencies are picked up early.

Wizard based deployment.

=== Configuration management
The user interface will provide an interactive way to view and change service configuration and to push these changes out to the running services. Broad range of configuration options will be made available and documented for each service. The expertise of Stackable will allow for richer health checks/sanity checks/configuration validation.

== Security and Governance
Stackable will be able to provide guided installation of secured services with the minimum of manual intervention.

Enable all security features

Security posture evaluation with suggestions on how to improve the security of deployed services.

Stackable will provide bulletins warning of new security issues and remediation steps including patches. These bulletins will be published on the web, delivered by email and published to a feed that can be read into the UI to provide operators with the information directly.

== Use Cases
=== Demo Applications
A library of fully working demos to show off the capabilities of Stackable. These will cover a number of use cases in different verticals.

* Platform deployment demo for operators
* Demo applications and use cases
** Streaming
** Machine Learning
** Data visualisation
** Big data analysis
** Big data query