= Maturity Level 5
Jim Halfpenny <jim@source321.com>
v1.0, 04.05.2021
:status: draft
:toc:
:icons: font

*Status*: {status}

== Objective
Maturity level 5 will deliver a fully-managed best of breed platform. Continuing to build on the existing platform new enhancements such as predictive maintenance, workload analysis, cost management and secure multi-tenancy. An ecosystem of components from Stackable and the wider community will make this the premier open source data processing platform.


== Features
=== Services
The list of services

=== Proposed list of services to be added
Few new services will be added at this stage as the collection of available services should be completed. The process of adding new operators to the platform should be mature enough that new services can be easily adopted.

User applications as operators


=== Upgrades
Upgrade dependencies - Manage all the knock on effects.
Upgrade individual components as seamlessly as possible.
Make upgrades easy.
Checkpoints and rollbacks.


=== Automated Provisioning

=== Configuration management

* Feedback loop, identify tuning and scaling opportunities.
* Fully fledged control plane. Deployment should be as easy as cloud native from the control plane.

== Security and Governance

=== Demo Applications

