= ADR022: Spark history server
Sönke Liebau <soenke.liebau@stackable.de>
v0.1, 2022-08-23
:status: pending

* Status: {status}
* Deciders:
** Andrew Kenworthy
** Sebastian Bernauer
** Razvan Mihai
* Date: 2022-08-23

== Context and Problem Statement

TODO (later)

== Decision Drivers

* Support multiple history servers.
* Integrate with the Stackable platform resource handling for S3 storage.
* Ease of use / intuitive / checked

== Considered Options
(refine/remove later?)
* 1. 
* 2. 

== Decision Outcome

Chosen option: TODO (after presentation to/consultation with team)

== Pros and Cons of the Options <!-- optional -->

=== History Server CRD referenced by SparkApplication

Example:
[source,yaml]
----
# Namespaced
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkHistoryServer
metadata:
  name: history
  namespace: default
spec:
  version: 3.3.0-stackable0.1.0
  properties: # list TODO names, objects?
    - # compaction
    - # retention/ttl
    - # update interval
    - # cleaner on/off - struct with default values?
    - ...
  cleaner: true | false # option of bool; default=false: sets spark.history.fs.cleaner.enabled=true
  # complex enum with variant s3 (hdfs later on)
  logFileDirectory:
    s3:
      prefix: eventlogs/
      bucket: spark-eventlogs # S3BucketDef
        inline:
          bucketName: spark-eventlogs
          connection:
            inline:
              host: minio
              port: 9000
              accessStyle: Path
              credentials:
                secretClass: history-server-s3-credentials
---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: spark
  namespace: default
spec:
  version: "1.0"
  sparkImage: docker.stackable.tech/stackable/spark-k8s:3.3.0-stackable0.1.0
  mode: cluster
  eventLogs: # Optional complex enum. Currently only supports a reference to a history server
    historyServer: history # reference, see above
  s3Connection: # Optional. Used for normal data operations.
    inline:
      host: minio
      port: 9000
      accessStyle: Path
      credentials:
        secretClass: application-s3-credentials

# SparkApplication will read the host and port (endpoint) from the HistoryServer and assert that it's the same as given in the normal "data" s3Connection.
# Afterwards it will set "spark.eventLog.enabled true" and (in case of S3)
# spark.eventLog.dir s3a://<build from SparkHistoryServer.eventLogs.s3.bucket.bucketName and SparkHistoryServer.eventLogs.s3.prefix>
----

=== Features (name?)

- history server and data sources are intentionally constrained to use the same common endpoint
  - future extension (addition of new fields) will involve only non-breaking changes (which would not be the case if separate distinct sources were implemented as a first step and then reversed later)
  - removes danger of false configuration
