= ADR028: Platform release support policy
Sebastian <sebastian.bernauer@stackable.tech>
v0.1, 2023-05-08
:status: draft

* Status: {status}
* Contributors:
** Andrew Kenworthy
** Felix Hennig
** Lars Francke
** Maximilian Wittich
** Malte Sander
** Natalie Klestrup Röijezon
** Razvan Mihai
** Sebastian Bernauer
** Sönke Liebau
** Vladislav Supalov
* Date: 2023-05-08

== Context and Problem Statement

// Describe the context and problem statement, e.g., in free form using two to three sentences. You may want to articulate the problem in form of a question.

Users of the Stackable platform often times want to stay on a specific product version - sometime also platform version.
While staying on a specific set of versions would theoretically work, the customers often want security updates, hence the reason we need to maintain older versions - for operators as well as product versions.

We currently don't have CRD versioning yet, this will be added in the future.

Currently we do support the last 3 Kubernetes versions.

== Decision Drivers

* Customer requirements for stability, but also security updates
* Maintenance/support effort

== Considered Options

=== No LTS versions
We don't have any LTS release.
Instead we support the last *X* releases, so users have approx. *X* months of time to upgrade the operators.

==== Pros
* Makes our live easy

==== Cons

=== Time-based LTS versions
We mark specific Stackable releases (e.g. the first within a year) as LTS release.
We do support them for *X* months.

==== Pros
* If customers stick to an old Kubernetes version and we try to force them to bump the operator version (and keep the product version) the operator might not support the old Kubernetes version

==== Cons
* Maintenance/support effort

=== LTS CRD versions
Alpha API versions may be removed in any release without prior deprecation notice.

Beta API versions are deprecated at a minimum of *1* platform releases after introduction and removed at a minimum of *1* platform releases after deprecation.

GA (stable) API versions are deprecated at a minimum of *2* platform releases after introduction and removed at a minimum of *1* platform releases after deprecation.

In addition to the CRD versions we support the operators of the last *2* releases, so users have approx. *6* months of time to upgrade the operators.

CRD versions look like, e.g. for ZookeeperCluster:

* v1alpha1
* v1alpha2
* v1beta1
* v1beta2
* v1
* >>> Release 23.7 happens
* v2alpha1
* >>> Release 24.1 happens
* We can also skip beta if we want:
* v2
* Or go directly to the next GA version:
* v3
* >>> Release 24.4 happens
* >>> Release 24.7 happens

Every release notes for a Stackable platform release contains something similar to the following:

*Release 23.7*

Added CRD versions:

* ZookeeperCluster v1alpha2
* ZookeeperCluster v1beta2
* ZookeeperCluster v1

*Release 24.1*

Added CRD versions:

* ZookeeperCluster v2alpha1

Removed CRD versions:

* ZookeeperCluster v1alpha2

Deprecated CRD versions:

* ZookeeperCluster v1beta2

*Release 24.4*

Added CRD versions:

* ZookeeperCluster v2
* ZookeeperCluster v3

Removed CRD versions:

* ZookeeperCluster v1beta2

Deprecated CRD versions:

* ZookeeperCluster v1

*Release 24.7*

Removed CRD versions:

* ZookeeperCluster v1 => If a customer really needs this version he can pay us to not remove the version in this release. It will stay deprecated and will be removed in a future once the customer does not pay us sufficient money any more.

Open questions: How do we handle support questions for deprecated versions?


==== Pros

==== Cons

== Decision Outcome

Option <<LTS CRD versions>> was chosen.
