= ADR9000: LTS version strategy
Sebastian <sebastian.bernauer@stackable.tech>
v0.1, 2023-05-08
:status: draft

* Status: {status}
* Contributors:
** TODO
* Date: 2023-05-08

== Context and Problem Statement

// Describe the context and problem statement, e.g., in free form using two to three sentences. You may want to articulate the problem in form of a question.

Users of the Stackable platform often times want to stay on a specific product version - sometime also platform version.
While staying on a specific set of versions would theoretically work, the customers often want security updates, hence the reason we need to maintain older versions - for operators as well as product versions.

We currently don't have CRD versioning yet, this will be added in the future.

Currently we do support the last 3 Kubernetes versions.

== Decision Drivers

* Customer requirements for stability, but also security updates
* Maintenance/support effort

== Considered Options

=== Stackable Release: Time-based LTS versions
We mark specific Stackable releases (e.g. the first within a year) as LTS release.
We do support them for *X* months.

==== Pros
* If customers stick to an old Kubernetes version and we try to force them to bump the operator version (and keep the product version) the operator might not support the old Kubernetes version

==== Cons
* Maintenance/support effort

=== Stackable Release: LTS CRD versions


==== Pros

==== Cons

=== Stackable Release: No LTS versions
We don't have any LTS release.
Instead we support the last *X* releases, so users have approx. *X* months of time to upgrade the operators.

==== Pros
* Makes our live easy

==== Cons

== Decision Outcome

TODO
