= [Worker Node Directories]
The Stackable Engineers
v0.1, 25.08.2021
:status: [draft | rejected | accepted | deprecated | … | superseded by link:0005-example.md[ADR-0005]]

* Status: {status}
* Deciders: [list everyone involved in the decision] <!-- optional -->
* Date: [YYYY-MM-DD when the decision was last updated] <!-- optional -->

Technical Story: [description | ticket/issue URL] <!-- optional -->

== Context and Problem Statement

A number of directories are needed and used by different components of the Stackable solution. These directories are used for logs, secrets, configuration, user data and other stuff. 
The question manifold, touching topics like coordination, identity and authentorization: Who should create, own, access and use which directories and when, in order to create a secure solution and accommodate the requirements of (enterprise) users. 

== Decision Drivers <!-- optional -->

* coordination: which process should when be allowed to create directories
* identity: 
* authorization: the "need-to-know" principle restricts the accessibility of information to the minimum 
* users/customers: they might restrict acceptable directories, creating the need to flexibly configure directories 
* shared access: two or more components might need to share a directory. one case is that multiple components share a common parent directory.  
* sequentiality: some component might want to access a directory owned and created by another component. some component might needs to create a directory ahead of time which will be primarily used or owned by another component

== Considered Options

* components can create and use whatever directories they want
* components have private directories and sharing is the exception, however will be allowed on a per case basis 
* a centralized component is responsible to provide directories and access to 
* container-approach: every component will find symlinked directories in a dedicated directory structure and thus accesses shared directories

== Decision Outcome

Chosen option: "[option 1]", because [justification. e.g., only option, which meets k.o. criterion decision driver | which resolves force force | … | comes out best (see below)].

=== Positive Consequences <!-- optional -->

* [e.g., improvement of quality attribute satisfaction, follow-up decisions required, …]
* …

=== Negative Consequences <!-- optional -->

* [e.g., compromising quality attribute, follow-up decisions required, …]
* …

== Pros and Cons of the Options <!-- optional -->

=== [option 1]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

=== [option 2]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

=== [option 3]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

== Links <!-- optional -->

* [Link type] [Link to ADR] <!-- example: Refined by [ADR-0005](0005-example.md) -->
* … <!-- numbers of links can vary -->