= [Supported Kubernetes versions]
The Stackable Engineers
v0.1, 25.08.2021
:status: [draft | rejected | accepted | deprecated | … | superseded by link:0005-example.md[ADR-0005]]

* Status: {status}
* Deciders: [list everyone involved in the decision] <!-- optional -->
* Date: [YYYY-MM-DD when the decision was last updated] <!-- optional -->

Technical Story: [Document supported Kubernetes versions| https://github.com/stackabletech/documentation/issues/83]
Related Documentation: https://docs.stackable.tech/agent/limitations.html

== Context and Problem Statement

=== Kubernetes Version Policy

Multiple new versions of Kubernetes are released every year (currently 3). Security fixes might come in between. Different Kubernetes components (including kubectl) will only support a limited number of versions, as mandated by kubernetes' https://kubernetes.io/releases/version-skew-policy/[Version Skew Policy]. Therefore, we need to define the supported Kubernetes versions. 

=== Deprecation and Removal of older resource variants 

It must be expected, that older versions of resource definitions, especially those which are pre-general-availability will be removed at some point. This was actually pushed through for the first time with kubernetes 1.22. All removed resources (actually the version-specific resource definitions and API endpoints) become incompatible and unsupported with 1.22 going forward. They need to be moved newer versions of the RDs and endpoints.

Such behavior can now be expected more often as new kubernetes releases come out.

=== Stackables behavior

The Stackable services (agent and operators) support only a small subset of Kubernetes versions. The reason is that, as pointed out already, the kubernetes API and tools restrict support of backward compatibility. Our software is compiled against a specific Kubernetes versionm but run on all other versions if no breaking change is actually used. 

Since with kubernetes 1.22, a backward compatibility breaking change was introduced, our software (like some others in the kubernetes ecosystem) broke for the removed stuff. Such a breaking change was hit in the agent when the endpoint certificates.k8s.io/v1beta1 was moved to certificates.k8s.io/v1 in Kubernetes v1.22 (see https://github.com/stackabletech/agent/pull/267[agent issue 267]). With this change, Kubernetes v1.18 and lower were not supported anymore.

It would be possible to provide several artifacts of the agent for different Kubernetes versions, e.g. agent-1.0.0-k1_18 and agent-1.0.0-k1_22, but it was decided that the effort is not necessary for now. Furthermore the services must be tested against all supported Kubernetes versions which creates additional effort (see https://github.com/stackabletech/t2/issues/126[issue "k8s version as an attribute in the cluster definition"]).

== Decision Drivers

* some customers told us they have troubles keeping the pace at which Kubernetes moves. They are only slowly adopting new Kubernetes releases, or even refrain completely from using Kubernetes. Customers might even be lagging behind in their Kubernetes clusters.
* tech is fast moving: major Kubernetes improvements are released multiple times a year
* managed Kubernetes offerings (GKE & Co.) typically only support fairly recent k8s releases   
* How can we upgrade the Kubernetes we run without customer intervention?

== Considered Options

* follow Kubernetes Version Skew Policy
    - needs an outline of migration strategy, announcements, communications and paths 
* support any Kubernetes Version for n months
    - needs an outline of migration strategy
* identify Stackable's own long-term-support version of Kubernetes
    - outline additional effort, like handling of security patches, and how to deal with missing new mainstream features 
* abandon Kubernetes
    - still needs some migration strategy nonetheless

== Decision Outcome

Chosen option: "[option 1]", because [justification. e.g., only option, which meets k.o. criterion decision driver | which resolves force force | … | comes out best (see below)].

=== Positive Consequences <!-- optional -->

* [e.g., improvement of quality attribute satisfaction, follow-up decisions required, …]
* …

=== Negative Consequences <!-- optional -->

* [e.g., compromising quality attribute, follow-up decisions required, …]
* …

== Pros and Cons of the Options <!-- optional -->

=== [option 1]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

=== [option 2]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

=== [option 3]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

== Links <!-- optional -->

* [Link type] [Link to ADR] <!-- example: Refined by [ADR-0005](0005-example.md) -->
* … <!-- numbers of links can vary -->