= [short title of solved problem and solution]
The Stackable Engineers
v0.1, 25.08.2021
:status: [draft | rejected | accepted | deprecated | … | superseded by link:0005-example.md[ADR-0005]]

* Status: {status}
* Deciders: [list everyone involved in the decision] <!-- optional -->
* Date: [YYYY-MM-DD when the decision was last updated] <!-- optional -->

Technical Story: [description | ticket/issue URL] <!-- optional -->

== Context and Problem Statement

A number of directories are needed and used by different components of the Stackable solution. These directories for example are used for logs, secrets, configuration and user data. 
The question is who show create, own, access and use which directories and when, in order to create a secure solution and accommodate the requirements of our (enterprise) users. 

== Decision Drivers <!-- optional -->

* security: the "need-to-know" principle restricts the accessibility of information to the minimum 
* users: they might restrict acceptable directories, creating the need to flexibly configure directories 
* shared access: some 
* sequentiality: some component might want to access a directory own and created by another component

== Considered Options

* [option 1]
* [option 2]
* [option 3]
* … <!-- numbers of options can vary -->

== Decision Outcome

Chosen option: "[option 1]", because [justification. e.g., only option, which meets k.o. criterion decision driver | which resolves force force | … | comes out best (see below)].

=== Positive Consequences <!-- optional -->

* [e.g., improvement of quality attribute satisfaction, follow-up decisions required, …]
* …

=== Negative Consequences <!-- optional -->

* [e.g., compromising quality attribute, follow-up decisions required, …]
* …

== Pros and Cons of the Options <!-- optional -->

=== [option 1]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

=== [option 2]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

=== [option 3]

[example | description | pointer to more information | …] <!-- optional -->

* Good, because [argument a]
* Good, because [argument b]
* Bad, because [argument c]
* … <!-- numbers of pros and cons can vary -->

== Links <!-- optional -->

* [Link type] [Link to ADR] <!-- example: Refined by [ADR-0005](0005-example.md) -->
* … <!-- numbers of links can vary -->