= Container environment

All Stackable-managed products regularly log information about their operating
environment, such as available disk interfaces and network interfaces.

This logging is performed by our https://github.com/stackabletech/containerdebug[containerdebug{external-link-icon}^] tool.

NOTE: This tool is intended as a debugging aid, and the particular information or
format should not be considered stable.

== Interval

The tool collects and logs the state of the container every 30 minutes. It can also
be triggered manually, by running the `containerdebug` command inside of the
main product container.

== Output

The collected information is logged to the Kubernetes pod logs (readable via `kubectl logs <pod>`)
and to the xref:observability/logging.adoc#architecture[shared Stackable log dir]
(for pickup by the Vector log agent).

Additionally, it is written as JSON to `/stackable/log/containerdebug-state.json`.
This file only contains the output from the _latest_ containerdebug run.
