# Authentication with OpenLDAP

Prerequisites:
- a k8s cluster
- stackablectl installed


## Install the latest Stackable release

[source,bash]
include::example$ldap-auth/10-install-release.sh[tag=stackablectl-release-install]

We install the release as a first step just so we have all our operators

## Setup Superset

Follow the getting started tutorial for superset to set up a basic instance (TODO: Link guide)

In Short:

[source,bash]
include::example$ldap-auth/20-setup-bitnami.sh[tag=add-bitnami-repo]

[source,bash]
include::example$ldap-auth/20-setup-bitnami.sh[tag=install-bitnami-psql]

A secret with the necessary credentials must be created: this contains database connection credentials as well as an admin account for Superset itself. Create a file called `superset-credentials.yaml`:

[source,yaml]
include::example$ldap-auth/superset-credentials.yaml[]

And apply it:

[source,bash]
include::example$ldap-auth/30-superset-base.sh[tag=apply-superset-credentials]

A Superset node must be created as a custom resource, create file called `superset.yaml`:

[source,yaml]
include::example$ldap-auth/superset/superset-no-ldap.yaml[]

And apply it:

[source,bash]
include::example$ldap-auth/30-superset-base.sh[tag=apply-superset-cluster]

A Kubernetes job is created which starts a pod to initialize the database. This can take a while.

You can use kubectl to wait on the resource:

[source,bash]
include::example$ldap-auth/30-superset-base.sh[tag=wait-supersetdb]

When the Superset node is created and the database is initialized, Superset can be opened in the
browser.

The Superset port which defaults to `8088` can be forwarded to the local host:

[source,bash]
include::example$ldap-auth/30-superset-base.sh[tag=port-forwarding]

Then it can be opened in the browser with `http://localhost:8088`.

Enter the admin credentials from the Kubernetes secret, you should be able to log in.

== Install OpenLDAP with the Stackable stack

[source,bash]
include::example$ldap-auth/40-install-openldap.sh[tag=install-openldap]


[source,yaml]
include::example$ldap-auth/bind-credentials-secret.yaml[]

[source,bash]
include::example$ldap-auth/40-install-openldap.sh[tag=apply-bind-credentials-secret]


[source,yaml]
include::example$ldap-auth/bind-credentials-secretclass.yaml[]

[source,bash]
include::example$ldap-auth/40-install-openldap.sh[tag=apply-credentials-secretclass]


[source,yaml]
include::example$ldap-auth/ldap-authenticationclass.yaml[]

[source,bash]
include::example$ldap-auth/40-install-openldap.sh[tag=apply-ldap-authenticationclass]

The tutorial-openLDAP is running inside the cluster, at the `openldap` service.
It has an admin/bind user with credentials ...
And users alice, bob with credentials ...


3. setup Authenticationclass etc.

create all the yamls

4. Connect products

refernce the AuthClass in superset, NiFi, etc. ...

5. Try it!

Log in with alice:alice or bob:bob

