= Authentication with OpenLDAP

Prerequisites:
- a k8s cluster
- stackablectl installed
- a basic knowledge of how to create resources in Kubernetes


You should already be familiar with setting up basic instances of Stackable supported products.
In this tutorial you will need to set up a Superset and Trino cluster. You can follow the getting started guides
for these products to learn how to do it.


== Install the latest Stackable release

[source,bash]
include::example$ldap-auth/10-install-release.sh[tag=stackablectl-release-install]

We install the release as a first step just so we have all our operators

## Setup Superset

Follow the getting started tutorial for superset to set up a basic instance (TODO: Link guide).
Your Superset cluster definition should look similar to this one:

[source,yaml]
include::example$ldap-auth/superset/superset-no-ldap.yaml[]

In the Secret `superset-credentials` that is referenced in the SupersetCluster, you have
defined admin credentials for logging into superset. Go to the web interface and make sure you
can use these credentials to log into Superset.

Shut down the superset cluster for now, as we will modify it and start it again later.

[source,bash]
include::example$ldap-auth/30-superset-base.sh[tag=delete-superset]

== Install OpenLDAP with the Stackable stack

[source,bash]
include::example$ldap-auth/40-install-openldap.sh[tag=install-openldap]

The tutorial-openLDAP is running inside the cluster, at the `openldap` service.
It has an admin/bind user with credentials ...
And users alice, bob with credentials ...


3. setup Authenticationclass etc.

create all the yamls

[source,yaml]
include::example$ldap-auth/bind-credentials-secret.yaml[]

[source,bash]
include::example$ldap-auth/40-install-openldap.sh[tag=apply-bind-credentials-secret]


[source,yaml]
include::example$ldap-auth/bind-credentials-secretclass.yaml[]

[source,bash]
include::example$ldap-auth/40-install-openldap.sh[tag=apply-credentials-secretclass]


[source,yaml]
include::example$ldap-auth/ldap-authenticationclass.yaml[]

[source,bash]
include::example$ldap-auth/40-install-openldap.sh[tag=apply-ldap-authenticationclass]


== Add OpenLDAP authentication to Superset

Update your superset defintion to reference the authenticationclass

[source,yaml]
include::example$ldap-auth/superset/superset-yes-ldap.yaml[]

Now deploy the updated superset cluster:

[source,bash]
include::example$ldap-auth/50-superset-with-ldap.sh[tag=apply-superset-cluster]

Connect with port-forwarding as before

[source,bash]
include::example$ldap-auth/50-superset-with-ldap.sh[tag=port-forwarding]

and log in. Notice that the `admin` user cannot be used anymore. It is a Superset internal user.
You can now log in with one of the OpenLDAP users, either alice or bob!

== Connect Trino

You can now use the `openldap` AuthenticationClass in other products as well.

[source,yaml]
include::example$ldap-auth/trino.yaml[]


[source,bash]
include::example$ldap-auth/60-trino.sh[tag=apply-superset-cluster]

TODO


==

5. Try it!

Log in with alice:alice or bob:bob

