= Authentication with OpenLDAP

The Stackable platform supports user authentication with LDAP in multiple products. 

Prerequisites:

* a k8s cluster
* stackablectl installed
* a basic knowledge of how to create resources in Kubernetes


You should already be familiar with setting up basic instances of Stackable supported products.
In this tutorial you will need to set up a Superset and Trino cluster. You can follow the getting started guides
for these products to learn how to do it.


== Setup

This tutorial guides you through configuring a Superset and Trino cluster to use LDAP. To make it easier, start with a Stackable provided example stack. Run:

[source,bash]
include::example$ldap-auth/10-install-base.sh[tag=stackablectl-install]

This command will install the latest Stackable release for you, and set up a Superset connected to a Trino, and all their dependencies.

Be patient, this might take 5 minutes or so. Get a coffee.

=== Inspect

Have a look aroud ...

Use `stackablectl svc list` to find the endpoints of Superset and Trino and open their web interfaces in the Browser.

You can log into Superset with user _admin_ and password _admin_, and into Trino with user _admin_ and password _adminadmin_.

These are the current users defined in Supersets and Trinos internal user management. You will see that these users cannot be used for authentication anymore after LDAP authentication has been enabled.

== Steps

The steps are:

* Install the demo OpenLDAP Stackable stack
* Configure an AuthenticationClass with this LDAP installation
* Update the SupersetCluster to use the AuthenticationClass to authenticate users
* Update the TrinoCluster to use the AuthenticationClass to authenticate users

=== Setup LDAP

Install the stack + configure things

==== Install OpenLDAP with the Stackable stack

[source,bash]
include::example$ldap-auth/30-install-openldap.sh[tag=install-openldap]

The tutorial-openLDAP is running inside the cluster, at the `openldap` service.
It has an admin/bind user with credentials ...
And users alice, bob with credentials ...

==== Create AuthenticationClass and related resources

The AuthenticationClass is the main resource required to configure the products, but it depends on some other resources. Below you will create a Secret, SecretClass and the AuthenticationClass.

NOTE: If you're having problems here, install the `openldap` stack instead of `tutorial-openldap` which comes with an already configured AuthenticationClass ready to use. You can then skip to <<superset, configuring superset>>.

First, create a secret that contains the LDAP bind credentials which products can use to authenticate with LDAP:

[source,yaml]
include::example$ldap-auth/bind-credentials-secret.yaml[]

[source,bash]
include::example$ldap-auth/30-install-openldap.sh[tag=apply-bind-credentials-secret]

Notice the secretclass annotation.

Create the SecretClass now:

[source,yaml]
include::example$ldap-auth/bind-credentials-secretclass.yaml[]

[source,bash]
include::example$ldap-auth/30-install-openldap.sh[tag=apply-credentials-secretclass]

This level of indirection is necessary, because the AuthenticationClass is cluster-scoped but Secrets are not. To learn more have a look at ...

Now you can create the AuthenticationClass `openldap` which references the SecretClass:

[source,yaml]
include::example$ldap-auth/ldap-authenticationclass.yaml[]

[source,bash]
include::example$ldap-auth/30-install-openldap.sh[tag=apply-ldap-authenticationclass]

remember the name of the AuthenticationClass (`openldap`), you will use it in the next steps when configuring the products.

[#superset]
=== Add LDAP authentication to Superset

To make Superset use your new LDAP AuthenticationClass, you have to update the SupersetCluster definition. A SupersetCluster named `superset` is already installed by the stack. 

Fetch the existing SupersetCluster defintion from the Kubernetes API server and save it into a `superset.yaml` file:

[source,bash]
include::example$ldap-auth/40-modify-superset.sh[tag=get-superset-yaml]

.The `superset.yaml` file should look similar to this
[%collapsible]
====
[source,yaml]
----
---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
  ...
spec:
  version: ...
  statsdExporterVersion: ...
  credentialsSecret: superset-credentials
  nodes:
    roleGroups:
      default:
        config:
  ...
----
====

You can now delete the SupersetCluster, we will recreate it later with the new configuration:

[source,bash]
include::example$ldap-auth/40-modify-superset.sh[tag=delete-superset]

Modify your `superset.yaml` to include this new `authenticationConfig` property under the `spec`:

[source,yaml]
include::example$ldap-auth/superset-auth-snippet.yaml[tag=snippet]

<1> The new `authenticationConfig` section which configures how Superset is authenticating users
<2> The `authenticationClass` property is referencing the AuthenticationClass `openldap` you created earlier
<3> The default Superset role that users should be assigned to when they log in. Any user will be an Admin

.Your `superset.yaml` should now look similar to this
[%collapsible]
====
[source,yaml]
----
---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
  ...
spec:
  version: ...
  statsdExporterVersion: ...
  credentialsSecret: superset-credentials
  authenticationConfig:
    authenticationClass: openldap
    userRegistrationRole: Admin
  nodes:
    roleGroups:
      default:
        config:
  ...
----
====

Now deploy the updated superset cluster:

[source,bash]
include::example$ldap-auth/40-modify-superset.sh[tag=apply-superset-cluster]


Connect to superset as before, and try logging in again with username _admin_ and password _admin_, Superset will not accept these credentials anymore. You now have to use LDAP credentials to log in. The OpenLDAP you installed earlier comes with two users, _alice_ (password _alice_) and _bob_ (password _bob_). Log in with any of these users and Superset will accept.

[#trino]
=== Add LDAP configuration to Trino

Trino is configured very similarly to Superset.

Fetch the existing TrinoCluster defintion from the Kubernetes API server and save it into a `trino.yaml` file:

[source,bash]
include::example$ldap-auth/60-modify-trino.sh[tag=get-yaml]

.The `trino.yaml` file should look similar to this
[%collapsible]
====
[source,yaml]
----
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
  ...
spec:
  version: 396-stackable0.1.0
  authentication:
    method:
      multiUser:
        ...
  opa:
    configMapName: opa
    package: trino
  catalogLabelSelector:
    ...
  workers:
    ...
  coordinators:
    ...
  ...
----
====

You can now delete the TrinoCluster, we will recreate it later with the new configuration:

[source,bash]
include::example$ldap-auth/60-modify-trino.sh[tag=delete]

Replace the `multiUser` authentication method in your `trino.yaml` with an `ldap` method that references the `openldap` AuthenticationClass:

[source,yaml]
include::example$ldap-auth/trino-auth-snippet.yaml[tag=snippet]

<1> The new `ldap` authentication method replaces the previous `multiUser` authentication method
<2> The `authenticationClass` property is referencing the AuthenticationClass `openldap` you created earlier

.Your `trino.yaml` should now look similar to this
[%collapsible]
====
[source,yaml]
----
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
  ...
spec:
  version: 396-stackable0.1.0
  authentication:
    method:
      ldap:
        authenticationClass: openldap
  opa:
    configMapName: opa
    package: trino
  catalogLabelSelector:
    ...
  workers:
    ...
  coordinators:
    ...
  ...
----
====

Now deploy the updated Trino cluster:

[source,bash]
include::example$ldap-auth/60-modify-trino.sh[tag=apply]

Again, like with Superset, connect to Trino now (make sure that the StatefulSets are running). You will notice that the _admin_ user cannot be used anymore, but the LDAP users _alice_ and _bob_ work!

TODO verify that it works in the script using the Trino CLI https://trino.io/docs/current/client/cli.html#username-and-password-authentication 

=== OPA

TODO The OPA step is not documented yet. But it's not really relevant, maybe just skip it?

5. Try it!

Log in with alice:alice or bob:bob

== Summary

To summarize you have done the following:

* Written an AuthenticationClass for an existing LDAP server. The credentials are stored in a Secret with a SecretClass that is referenced in the AuthenticationClass.
* Adapted the SupersetCluster spec to include the reference to the LDAP AuthenticationClass.
* Adapted the TrinoCluster spec to include the reference to the AuthenticationClass.

The LDAP connection details only needed to be written down once, in the AuthenticationClass. Making a product use this AuthenticationClass is then done by referencing it, so the configuration for LDAP is all in a single resource.

== Further Reading

- Concept page
- Operator docs
- AuthenticationClass Reference