@startgantt
printscale monthly
Project starts the 2023-04-01

[23.4]  happens 2023-04-01
[23.7]  happens 2023-07-01 and displays on same row as [23.4]
[23.10] happens 2023-10-01 and displays on same row as [23.4]
[24.1]  happens 2024-01-01 and displays on same row as [23.4]
[24.4]  happens 2024-04-01 and displays on same row as [23.4]
[24.7]  happens 2024-07-01 and displays on same row as [23.4]
[24.10] happens 2024-10-01 and displays on same row as [23.4]
[25.1]  happens 2025-01-01 and displays on same row as [23.4]

-- Apache Airflow --
[2.2.3+4+5]    starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[2.2.3+4+5 ]   starts 2023-07-01 and ends 2023-10-01 and is colored in Khaki
[2.2.3+4+5 ]   displays on same row as [2.2.3+4+5]
[2.4.1]        starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[2.4.1 ]       starts 2023-07-01 and ends 2023-10-01 and is colored in Khaki
[2.4.1 ]       displays on same row as [2.4.1]
[2.6.0]        starts 2023-07-01 and ends 2023-10-01 and is colored in LightGreen
[2.6.x]        starts 2023-10-01 and ends 2024-01-01 and is colored in LightGreen
[2.6.x]        displays on same row as [2.6.0]
[2.6.x ]       starts 2024-01-01 and ends 2024-04-01 and is colored in LightGreen
[2.6.x ]       displays on same row as [2.6.0]
[2.6.x  ]      starts 2024-04-01 and ends 2024-07-01 and is colored in LightGreen
[2.6.x  ]      displays on same row as [2.6.0]

-- Apache Druid --
[0.23.0]       starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[0.23.0 ]      starts 2023-07-01 and ends 2023-10-01 and is colored in Khaki
[0.23.0 ]      displays on same row as [0.23.0]
[24.0.0]       starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[24.0.0 ]      starts 2023-07-01 and ends 2023-10-01 and is colored in Khaki
[24.0.0 ]      displays on same row as [24.0.0]
[25.0.0]       starts 2023-07-01 and ends 2023-10-01 and is colored in LightGreen
[25.0.x]       starts 2023-10-01 and ends 2024-01-01 and is colored in LightGreen
[25.0.x]       displays on same row as [25.0.0]
[25.0.x ]      starts 2024-01-01 and ends 2024-04-01 and is colored in LightGreen
[25.0.x ]      displays on same row as [25.0.0]
[25.0.x  ]     starts 2024-04-01 and ends 2024-07-01 and is colored in LightGreen
[25.0.x  ]     displays on same row as [25.0.0]

-- Apache HBase --
[2.4.6-12]     starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[2.4.6-12 ]    starts 2023-07-01 and ends 2023-10-01 and is colored in Khaki
[2.4.6-12 ]    displays on same row as [2.4.6-12]
[2.5.4]        starts 2023-07-01 and ends 2023-10-01 and is colored in LightGreen
[2.5.x]        starts 2023-10-01 and ends 2024-01-01 and is colored in LightGreen
[2.5.x]        displays on same row as [2.5.4]
[2.5.x ]       starts 2024-01-01 and ends 2024-04-01 and is colored in LightGreen
[2.5.x ]       displays on same row as [2.5.4]
[2.5.x  ]      starts 2024-04-01 and ends 2024-07-01 and is colored in LightGreen
[2.5.x  ]      displays on same row as [2.5.4]

-- Apache HDFS --
[3.2.2]        starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[3.2.2 ]       starts 2023-07-01 and ends 2023-10-01 and is colored in Khaki
[3.2.2 ]       displays on same row as [3.2.2]
[3.3.1+3+4]    starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[3.3.1+3+4 ]   starts 2023-07-01 and ends 2023-10-01 and is colored in Khaki
[3.3.1+3+4 ]   displays on same row as [3.3.1+3+4]
[3.3.5]        starts 2023-07-01 and ends 2023-10-01 and is colored in LightGreen
[3.3.x]        starts 2023-10-01 and ends 2024-01-01 and is colored in LightGreen
[3.3.x]        displays on same row as [3.3.5]
[3.3.x ]       starts 2024-01-01 and ends 2024-04-01 and is colored in LightGreen
[3.3.x ]       displays on same row as [3.3.5]
[3.3.x  ]      starts 2024-04-01 and ends 2024-07-01 and is colored in LightGreen
[3.3.x  ]      displays on same row as [3.3.5]

-- Apache Hive --
[2.3.9]        starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[2.3.9 ]       starts 2023-07-01 and ends 2023-10-01 and is colored in Khaki
[2.3.9 ]       displays on same row as [2.3.9]
[3.1.3]        starts 2023-04-01 and ends 2023-07-01 and is colored in LightGreen
[3.1.3 ]       starts 2023-07-01 and ends 2023-10-01 and is colored in LightGreen
[3.1.3 ]       displays on same row as [3.1.3]
[3.1.x ]       starts 2023-10-01 and ends 2024-01-01 and is colored in LightGreen
[3.1.x ]       displays on same row as [3.1.3]
[3.1.x  ]      starts 2024-01-01 and ends 2024-04-01 and is colored in LightGreen
[3.1.x  ]      displays on same row as [3.1.3]
[3.1.x   ]     starts 2024-04-01 and ends 2024-07-01 and is colored in LightGreen
[3.1.x   ]     displays on same row as [3.1.3]

-- Apache Kafka --
-- Apache NiFi --
-- Apache Spark on k8s --
-- Apache Superset --
-- Apache Zookeeper --
-- Trino --
-- Open policy agent --

@endgantt