---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: openldap-tls-ca # <1>
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: openldap-tls-ca # <2>
          namespace: default # <3>
        autoGenerate: false # <4>
