---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-tls-ca
  labels:
    secrets.stackable.tech/class: openldap-tls-ca # <1>
stringData:
  ca.crt: | # <2>
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
