== Release 26.3

=== 26.3.0

Released on 2026-03-16.
(Optional description / introduction)

==== New platform features

===== General

====== Miscellaneous

* In 26.3.0 we added new demo that shows Retrieval Augmented Generation (RAG) with OpenSearch as the vector store.
  Consult the xref:demos:opensearch-rag.adoc[demo documentation page] for more details.
  See https://github.com/stackabletech/demos/pull/354[demos#354].
* All remaining operators now maintain their own CRD(s) instead of relying on Helm as a deployment mechanism.
  Additionally, the conversion webhook is now running alongside the controller for future CRD versioning.
  Tracked in https://github.com/stackabletech/issues/issues/808[issues#808].
* This release supports `objectOverrides`, a list of generic Kubernetes objects, which are merged into the objects created by the operator (e.g. StatefulSets, Listeners or ConfigMaps).
  The priority of the overrides (in ascending order) is `configOverrides` -> `podOverrides` -> `objectOverrides`, with the latter overriding the previous.
  See the xref:concepts:overrides.adoc#object-overrides[concepts page] for more details.
  Tracked in https://github.com/stackabletech/issues/issues/712[issues#712].

==== Supported versions

===== Product versions

As with previous SDP releases, many product images have been updated to their latest versions.
Refer to the xref:operators:supported_versions.adoc[supported versions] documentation for a complete overview including LTS versions or deprecations.

====== New versions

The following new product versions are now supported:

* Apache Airflow: https://github.com/stackabletech/docker-images/issues/1416[3.1.6]
* Apache Druid: https://github.com/stackabletech/docker-images/issues/1371[35.0.1]
* Apache HBase: https://github.com/stackabletech/docker-images/issues/1372[2.6.4 (LTS)]
* Apache Hive: https://github.com/stackabletech/docker-images/issues/1375[4.2.0]
* Apache Kafka: https://github.com/stackabletech/docker-images/issues/1376[4.1.1 (experimental)]
** Note that Kafka 3.9.1 is the last version that supports Apache ZooKeeper as the metadata manager.
* Apache NiFi: https://github.com/stackabletech/docker-images/issues/1377[2.7.2]
** Note that this version supports Iceberg, but only with S3 and the Iceberg REST catalog.
   Hive metastore or HDFS are not supported.
   Read the https://docs.stackable.tech/home/nightly/nifi/usage_guide/writing-to-iceberg-tables/[official NiFi Iceberg documentation] for details.
* Apache Spark: https://github.com/stackabletech/docker-images/issues/1381[3.5.8 (LTS)], https://github.com/stackabletech/docker-images/issues/1381[4.1.1]
** Note that there are no Apache Iceberg and Delta runtime libraries available for 4.1.1 yet.
* Apache Superset: https://github.com/stackabletech/docker-images/issues/1382[6.0.0]
** OpenStreetView has been promoted as the new default for the Deck.gl visualization which doesn't require an API key.
** `AUTH_OID` will not longer be automatically imported in the superset_config.py, and is no longer available from Superset 6.0.0.
   If you are using Superset < 6.0.0 and still require `AUTH_OID`, you can manually import it by following the xref:superset:usage-guide/configuration-environment-overrides.adoc#_configuration_properties[documented instructions].
** Also consult the https://github.com/apache/superset/blob/6.0.0/UPDATING.md[official update notes].
* Open Policy Agent: https://github.com/stackabletech/docker-images/issues/1378[1.12.3]
* OpenSearch: https://github.com/stackabletech/docker-images/issues/1379[3.4.0]
* Trino: https://github.com/stackabletech/docker-images/issues/1383[479]
** The storage-connector is based on Trino 477 because there was no later release.
* Vector: https://github.com/stackabletech/docker-images/issues/1369[0.52.0]

====== Deprecated versions

The following product versions are deprecated and will be removed in a later release:

* Apache Druid: https://github.com/stackabletech/docker-images/issues/1371[34.0.0]
* Apache HBase: https://github.com/stackabletech/docker-images/issues/1372[2.6.3]
* Apache Hive: https://github.com/stackabletech/docker-images/issues/1375[4.1.0]
* Apache Spark: https://github.com/stackabletech/docker-images/issues/1381[3.5.7], https://github.com/stackabletech/docker-images/issues/1381[4.0.1]
* Open Policy Agent: https://github.com/stackabletech/docker-images/issues/1378[1.8.0]

====== Removed versions

The following product versions are no longer supported.
These images for released product versions remain available https://oci.stackable.tech/[here,window=_blank].
Information on how to browse the registry can be found xref:contributor:project-overview.adoc#docker-images[here,window=_blank].

* Apache Airflow: https://github.com/stackabletech/docker-images/issues/1370[2.10.5], https://github.com/stackabletech/docker-images/issues/1370[3.0.1]
* Apache Druid: https://github.com/stackabletech/docker-images/issues/1371[33.0.0]
* Apache HBase: https://github.com/stackabletech/docker-images/issues/1372[2.6.2]
* Apache Hadoop: https://github.com/stackabletech/docker-images/issues/1374[3.4.1]
* Apache Kafka: https://github.com/stackabletech/docker-images/issues/1376[3.7.2], https://github.com/stackabletech/docker-images/issues/1376[4.1.0]
* Apache NiFi: https://github.com/stackabletech/docker-images/issues/1377[1.27.0], https://github.com/stackabletech/docker-images/issues/1377[2.4.0]
* Apache Spark: https://github.com/stackabletech/docker-images/issues/1381[3.5.6]
* Apache Superset: https://github.com/stackabletech/docker-images/issues/1382[4.0.2], https://github.com/stackabletech/docker-images/issues/1382[4.1.2]
* Apache ZooKeeper: https://github.com/stackabletech/docker-images/issues/1384[3.9.3]
* Open Policy Agent: https://github.com/stackabletech/docker-images/issues/1378[1.4.2]
* Trino: https://github.com/stackabletech/docker-images/issues/1383[451], https://github.com/stackabletech/docker-images/issues/1383[476]
* Vector: https://github.com/stackabletech/docker-images/issues/1369[0.49.0]

===== Kubernetes versions

[WARNING]
====
There currently is one known issue when running on Kubernetes 1.35.
See the link:#known-issues-26_3_0[known issues] section below for more details.
====

This release supports the following Kubernetes versions:

* `1.35`
* `1.34`
* `1.33`
* `1.32`
* `1.31`

These Kubernetes versions are no longer supported:

* `1.30`
* `1.29`

===== OpenShift versions

This release is available in the RedHat Certified Operator Catalog for the following OpenShift versions:

* `4.20`
* `4.19`
* `4.18`

These OpenShift versions are no longer supported:

* `4.17`
* `4.16`

==== Upgrade from 25.11

[TIP]
====
Please consult the following upgrade notes when upgrading from 25.11 to 26.3:

* xref:opensearch:usage-guide/upgrade.adoc[OpenSearch upgrade guide]
====

===== Using stackablectl

====== Upgrade with a single command

Starting with stackablectl Release 1.0.0 the multiple consecutive commands described below can be shortened to just one command, which executes exactly those steps on its own.

[source,console]
----
$ stackablectl release upgrade 26.3
----

====== Upgrade with multiple consecutive commands

Uninstall the `25.11` release

[source,console]
----
$ stackablectl release uninstall 25.11

Uninstalled release '25.11'

Use "stackablectl release list" to list available releases.
# ...
----

Install the `26.3` release

[source,console]
----
$ stackablectl release install 26.3

Installed release '26.3'

Use "stackablectl operator installed" to list installed operators.
----

===== Using Helm

Use `helm list` to list the currently installed operators.

You can use the following command to uninstall all operators that are part of the `25.11` release:

[source,console]
----
$ helm uninstall airflow-operator <PRODUCT>-operator ...
release "airflow-operator" uninstalled
release "<PRODUCT>-operator" uninstalled
...
----

Install the `26.3` release

[NOTE]
====
`helm repo` subcommands are not supported for OCI registries.
The operators are installed directly, without adding the Helm Chart repository first.
====

[source,console]
----
helm install --wait <PRODUCT>-operator oci://oci.stackable.tech/sdp-charts/<PRODUCT>-operator --version 26.3.0
----

[#known-issues-26_3_0]
==== Known issues

* There is a https://github.com/kubernetes/kubernetes/issues/137409[known issue] with the feature gate https://github.com/kubernetes/kubernetes/pull/133153[MaxUnavailableStatefulSet] that is enabled by default as a beta feature in Kubernetes 1.35.
  This issue affects all SDP operators, especially the Trino operator. +
  To work around the issue there are two possibilities:
  . Disable this feature gate in your Kubenetes 1.35 clusters.
  . Ensure that your dev-ops pipelines create product custom resources (e.g. TrinoCluster, SparkApplication, etc.) last, after any referenced custom resources such as TrinoCatalog, S3Connection and so on.
