== Release 26.3

=== 26.3.0

Released on 2026-03-16.
(Optional description / introduction)

==== Supported versions

===== Kubernetes versions

[WARNING]
====
There currently is one known issue when running on Kubernetes 1.35.
See the link:#known-issues-26_3_0[known issues] section below for more details.
====

This release supports the following Kubernetes versions:

* `1.35`
* `1.34`
* `1.33`
* `1.32`
* `1.31`

These Kubernetes versions are no longer supported:

* `1.30`
* `1.29`

===== OpenShift versions

This release is available in the RedHat Certified Operator Catalog for the following OpenShift versions:

* `4.20`
* `4.19`
* `4.18`

These OpenShift versions are no longer supported:

* `4.17`
* `4.16`

[#known-issues-26_3_0]
==== Known issues

* There is a https://github.com/kubernetes/kubernetes/issues/137409[known issue] with the feature gate https://github.com/kubernetes/kubernetes/pull/133153[MaxUnavailableStatefulSet] that is enabled by default as a beta feature in Kubernetes 1.35.
  This issue affects all SDP operators, especially the Trino operator. +
  To work around the issue there are two possibilities:
  . Disable this feature gate in your Kubenetes 1.35 clusters.
  . Ensure that your dev-ops pipelines create product custom resources (e.g. TrinoCluster, SparkApplication, etc.) last, after any referenced custom resources such as TrinoCatalog, S3Connection and so on.
