== Release 25.11

=== 25.11.0

Released on YYYY-MM-DD.
(Optional description / introduction)

==== New platform features

===== General

====== Custom image selection

Previously, when using custom images in combination with a SHA digest like `oci.stackable.tech/sdp/spark-k8s@sha256:c8b7...`, all operators created invalid labels `app.kubernetes.io/version` for their applied resources.
This was fixed by checking and replacing invalid characters in the created labels when a SHA digest is used to select the custom image.
See https://github.com/stackabletech/operator-rs/pull/1076[operator-rs#1076].

====== Security

Traffic between Open Policy Agent (OPA) and clients can be encrypted using TLS by enabling it in the OPA custom resource.
The authorizers for Trino and NiFi automatically integrate with these secured OPA deployments and verify the authenticity of the server certificates when TLS for OPA is enabled.
See the xref:opa:usage-guide/tls.adoc[TLS encryption documentation page] and https://github.com/stackabletech/opa-operator/issues/581[opa-operator#581].

====== Miscellaneous

// TODO: Do we want to include this?
The performance of the Trino rules in the `end-to-end-security` stack was improved.
Batch queries are now significantly faster.
See https://github.com/stackabletech/demos/pull/289[demos#289].

===== Apache Airflow

* The Airflow xref:airflow:index.adoc#_triggerers[triggerer] component is now supported.
  This can be used with DAGs utilising deferrable operators to keep worker slots free and enhance HA.
  See https://github.com/stackabletech/airflow-operator/issues/200[airflow-operator#200].
* The xref:demos:airflow-scheduled-job.adoc[`airflow-scheduled-job`] demo for Airflow has been extended to showcase some of the new Airflow 3.x features in the context of SDP i.e. event scheduling (with Kafka), triggerer actions and user authorization with OPA and the SDP OPA authorizer.
  See https://github.com/stackabletech/demos/issues/223[demos#223].

===== Apache NiFi

A patch was added which allows disabling the SNI (Server Name Indication) checks for NiFi.
The workaround is documented in the xref:nifi:troubleshooting/index.adoc[troubleshooting] section.
This can be useful in certain scenarios where the external name is not in the certificates used by NiFi.
See https://github.com/stackabletech/nifi-operator/issues/812[nifi-operator#812].

===== Apache Spark

* The service account of spark applications can now be overridden with pod overrides.
  Previously, the application service account was passed as command line argument to spark-submit and it was therefor not possible to overwrite it with pod overrides for the driver and executors.
  This CLI argument has now been moved to the pod templates of the individual roles.
  See https://github.com/stackabletech/spark-k8s-operator/pull/617[spark-k8s-operator#617].
* This release adds experimental support for Spark 4.X.X.
  The support is marked as experimental because Spark 4.0.0 has known compatibility issues with https://github.com/apache/hbase-connectors/pull/130[Apache HBase] and https://github.com/apache/iceberg/issues/13358[Apache Iceberg].
  See https://github.com/stackabletech/spark-k8s-operator/issues/586[spark-k8s-operator#586].

====== Open Policy Agent

This release adds a dedicated per-rolegroup `-metrics` Service, which can be used to scrape Prometheus metrics.
// TODO: How do we expose more metrics? The PR this snippet comes from doesn't seem to expose more metrics.
// The Expose more Prometheus metrics, such as successful or failed bundle loads and information about the OPA environment
