== Release 25.11

=== 25.11.0

Released on YYYY-MM-DD.
(Optional description / introduction)

==== New platform features

===== General

====== Custom image selection

Previously, when using custom images in combination with a SHA digest like `oci.stackable.tech/sdp/spark-k8s@sha256:c8b7...`, all operators created invalid labels `app.kubernetes.io/version` for their applied resources.
This was fixed by checking and replacing invalid characters in the created labels when a SHA digest is used to select the custom image.
See https://github.com/stackabletech/operator-rs/pull/1076[operator-rs#1076].

====== Security

Traffic between Open Policy Agent (OPA) and clients can be encrypted using TLS by enabling it in the OPA custom resource.
The authorizers for Trino and NiFi automatically integrate with these secured OPA deployments and verify the authenticity of the server certificates when TLS for OPA is enabled.
See the xref:opa:usage-guide/tls.adoc[TLS encryption documentation page] and https://github.com/stackabletech/opa-operator/issues/581[opa-operator#581].

====== Miscellaneous

// TODO: Do we want to include this?
The performance of the Trino rules in the `end-to-end-security` stack was improved.
Batch queries are now significantly faster.
See https://github.com/stackabletech/demos/pull/289[demos#289].

===== Apache Airflow

* The Airflow xref:airflow:index.adoc#_triggerers[triggerer] component is now supported.
  This can be used with DAGs utilising deferrable operators to keep worker slots free and enhance HA.
  See https://github.com/stackabletech/airflow-operator/issues/200[airflow-operator#200].
* The xref:demos:airflow-scheduled-job.adoc[`airflow-scheduled-job`] demo for Airflow has been extended to showcase some of the new Airflow 3.x features in the context of SDP i.e. event scheduling (with Kafka), triggerer actions and user authorization with OPA and the SDP OPA authorizer.
  See https://github.com/stackabletech/demos/issues/223[demos#223].

===== Apache NiFi

A patch was added which allows disabling the SNI (Server Name Indication) checks for NiFi.
The workaround is documented in the xref:nifi:troubleshooting/index.adoc[troubleshooting] section.
This can be useful in certain scenarios where the external name is not in the certificates used by NiFi.
See https://github.com/stackabletech/nifi-operator/issues/812[nifi-operator#812].

===== Apache Spark

* The service account of spark applications can now be overridden with pod overrides.
  Previously, the application service account was passed as command line argument to spark-submit and it was therefor not possible to overwrite it with pod overrides for the driver and executors.
  This CLI argument has now been moved to the pod templates of the individual roles.
  See https://github.com/stackabletech/spark-k8s-operator/pull/617[spark-k8s-operator#617].
* This release adds experimental support for Spark 4.X.X.
  The support is marked as experimental because Spark 4.0.0 has known compatibility issues with https://github.com/apache/hbase-connectors/pull/130[Apache HBase] and https://github.com/apache/iceberg/issues/13358[Apache Iceberg].
  See https://github.com/stackabletech/spark-k8s-operator/issues/586[spark-k8s-operator#586].

====== Open Policy Agent

This release adds a dedicated per-rolegroup `-metrics` Service, which can be used to scrape Prometheus metrics.
// TODO: How do we expose more metrics? The PR this snippet comes from doesn't seem to expose more metrics.
// The Expose more Prometheus metrics, such as successful or failed bundle loads and information about the OPA environment

====== Trino

* The operator now supports configuring fault-tolerant execution for Trino via the TrinoCluster CRD.
  See the xref:trino:usage-guide/fault-tolerant-execution.adoc[documentation page] and https://github.com/stackabletech/trino-operator/pull/779[trino-operator#779].
* The Trino client spooling protocol can now be configured using the `spec.clusterConfig.clientProtocol.spooling` property.
// TODO: Is this an S3Connection (CR)?
  Users can configure an S3 connection and the location or spooling segments.
  Additional properties can be added using the `configOverrides` mechanism for the `spooling-manager.properties` file.
  See the xref:trino:usage-guide/client-spooling-protocol.adoc[client spooling protocol] documentation page and https://github.com/stackabletech/trino-operator/pull/793[trino-operator#793].

==== Platform improvements

===== Vulnerabilities

37 CVEs were fixed in the Stackable product images.
This includes 2 critical and 18 high-severity CVEs.

===== General

====== Observability

This release includes various improvements in regards to metrics collection and exposition.
Previously, some operators did not expose Prometheus annotations containing the HTTP(S) scheme or the metrics path and port.
These annotations are now available which allows custom relabel configs in Prometheus to scrape the metric endpoints.

* Apache HBase: The `prometheus.io/scrape` label is now only available on the `metrics` Service (instead of the `headless` service), which uses `metrics` as the port name instead of the previous `ui-http`/`ui-https` port name.
  See https://github.com/stackabletech/hbase-operator/pull/701[hbase-operator#701].
* Apache Airflow: The operator now adds the appropriate Prometheus annotations.
  See https://github.com/stackabletech/airflow-operator/pull/698[airflow-operator#698].
* Apache Druid: The operator now adds the appropriate Prometheus annotations.
  See https://github.com/stackabletech/druid-operator/pull/761[airflow-operator#761].

====== Miscellaneous

* All operators now correctly handle multiple CA certificates.
  This can be the case if the Stackable secret-operator auto rotated the CA certificate or if multiple CA certificates are present in a SecretClass.
  See https://github.com/stackabletech/issues/issues/764[issues#764] for more details.
* New Helm values have been added to the operators for setting `priorityClassName` on the resulting Pods, giving administrators greater control over scheduling.
  When left unconfigured, the fields will not be present on the subsequent Pods.
  See https://github.com/stackabletech/issues/issues/765[issues#765] for more details.
+
[source,yaml]
----
# Listener operator
csiProvisioner:
  priorityClassName: ...

csiNodeDriver:
  priorityClassName: ...

# TODO: List/check secret-operator here as well
# All other operators
priorityClassName: ...
----

* Previously, log entries for some supported products were broken from time to time.
  These issues have now been resolved by implementing multiple fixes in various affected (upstream) projects.
  See the tracking issue https://github.com/stackabletech/issues/issues/778[issues#778] for more details.
** Pull request https://github.com/vectordotdev/vector/pull/24028[vectordotdev/vector#24028] was raised to fix log entries with multi-char delimiters.
   At the time of writing, this PR has not been merged yet, but the fix is manually applied as a patch.
   See https://github.com/stackabletech/docker-images/pull/1323[docker-images#1323].
** A XMLLayout multithreading issue in logback has been fixed by raising https://github.com/qos-ch/logback/pull/978[qos-ch/logback#978].
    This fix has been rolled out in all affected products:
*** Apache Kafka: https://github.com/stackabletech/docker-images/pull/1330[docker-images#1330]
*** Apache NiFi: https://github.com/stackabletech/docker-images/pull/1314[docker-images#1314]
*** Apache ZooKeeper: https://github.com/stackabletech/docker-images/pull/1320[docker-images#1320]
