= Configuring the Kubernetes cluster domain
:description: Configure Stackable operators to use a different cluster domain other than 'cluster.local'.
:dns-custom-nameservers: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
:dns-pod-service: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

Stackable operators allow to configure a non-default cluster domain as described in {dns-custom-nameservers}[Customizing DNS Service] (and more in {dns-pod-service}[DNS for Services and Pods]).
The configuration is primarily done via an environment variable `KUBERNETES_CLUSTER_DOMAIN`, but there is also a mechanism to auto detect the cluster domain using the `/etc/resolv.conf` file.

The following steps explain the use of the environment variable and the auto detection mechanism in detail:

== Steps

=== Use environment variable

The environment variable `KUBERNETES_CLUSTER_DOMAIN` takes precedence over auto detection.
This means that the desired cluster domain can be configured in a Helm values file via the property `kubernetesClusterDomain` or via the install command like:

```
helm install hive-operator stackable-stable/hive-operator --set kubernetesClusterDomain="my-cluster.local"
```

=== Use auto detection

As a first step, the auto detection is checking the runtime environment of the operator. In most cases this is a clusterized environment like Kubernetes or Openshift.
This is determined by checking if the `KUBERNETES_SERVICE_HOST` environment variable is set in the operator Pod.

If clusterized, the auto detection parses the `/etc/resolv.conf` file for the last entry starting with the `search` keyword. Within that `search` entry the shortest option is selected.

An example for the `/etc/resolv.conf` in a Kubelet looks like:

```
nameserver 10.32.0.10
search <namespace>.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

Using this example as a base for the cluster domain auto detection, the operator would choose the `cluster.local` option.

=== Running locally

This section covers the case when both `KUBERNETES_CLUSTER_DOMAIN` and `KUBERNETES_SERVICE_HOST` are not set. This would be the case if the operator is not running in a clusterized environment like e.g. locally on a Laptop or PC.
Running the operator locally is mostly for development and therefore not relevant for most users.

If running locally, and `KUBERNETES_CLUSTER_DOMAIN` and `KUBERNETES_SERVICE_HOST` are not set, the operator will default its cluster domain to `cluster.local`.
