= New Product Version

== Checklist: adding a new supported product version

This page contains information on the steps that need to be taken when adding a new supported product version to our platform.

One or more new issues need to be created for each new version we want to support.

NOTE: _Support_ is used in the _technical_ meaning here.
This does not necessarily mean that we're going to provide enterprise support for this version to our customers.

In general these are the steps that need to be taken even though some of them are optional depending on what exactly needs to be done:

* Open a _tracking_ issue in the relevant operator repository
** This issue serves as the hub for all other issues that might have to be opened
** This issue should contain information like links to changelogs or release notes, it should also contain information on breaking changes and how they affect our operator etc.

* Provide an updated Docker image
** Open a separate issue in the https://github.com/stackabletech/docker-images/[Docker Images] repository

* Optional: Update the documentation include the newly supported version

* Optional: Update the integration tests to use the new version

* Optional: Update examples to use the new versions
