= Temporary credentials lifetime
:description: Customize the lifetime of temporary credentials.

== Usages

=== TLS certificates

Currently the only temporary credentials are TLS certificates.

Many products use TLS to secure the communications, often times customers use the xref:secret-operator:secretclass.adoc#backend-autotls[secret-operator autoTls] backend to create TLS certificates for the Pods on the fly.
For maximum security these temporary credentials have a short lifetime by default, which will result in e.g. your Trino coordinator restarting every ~24 hours (minus some safety buffer) to avoid using expired certificates.

== Configure the lifetime

In high load production environments, restarting Pods can be a costly operation, as it can disrupt services and in some cases even lead to data loss.
To avoid frequent restarts, the lifetime of all temporary credentials (such as the TLS certificates) can be increased as needed.

Here is an example for configuring the temporary credentials lifetime to 7 days in a HDFS stacklet.
It should result in the HDFS Pods restarting weekly instead of daily:

[source,yaml]
----
---
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs
spec:
  nameNodes:
    config:
      requestedSecretLifetime: 7d # <1>
    roleGroups:
      default:
        replicas: 2
  dataNodes:
    config:
      requestedSecretLifetime: 7d # <2>
    roleGroups:
      default:
        replicas: 2
  journalNodes:
    roleGroups:
      default:
        replicas: 3
        config:
          requestedSecretLifetime: 7d # <3>
----
<1> The lifetime of the TLS certificates for *all* NameNode roleGroups is set to 7 days.
<2> The lifetime of the TLS certificates for *all* DataNode roleGroups is set to 7 days.
<3> The lifetime of the TLS certificates for the `default` JournalNode group is set to 7 days.

NOTE: The configuration for the JournalNodes is done at roleGroup level for demonstration purposes.

=== TLS certificate lifetimes

Even though operators allow setting this property to a value of your choice, the xref:secret-operator:index.adoc[secret-operator] will not exceed the `maxCertificateLifetime` value specified in SecretClass creating the TLS certificates (see xref:secret-operator/secretclass.adoc#certificate_lifetime).

=== Operators supporting the lifetime configuration

Similar to the example above, users can configure the lifetime of temporary credentials for the following operators:

* Apache Druid
* Apache Hadoop
* Apache HBase
* Apache NiFi
* Apache Spark
* Apache Zookeeper
* Trino

== Check the lifetime

Pods are normally not restarted "randomly" by Stackable operators.
Instead, when a temporary credential is added to a Pod, an annotation is added as well.
It starts with `restarter.stackable.tech/expires-at.` and instructs the xref:commons-operator:index.adoc[commons-operator] to restart the Pod once the specified instant is reached.

Given the following Pod

[source,yaml]
----
kind: Pod
metadata:
  annotations:
    restarter.stackable.tech/expires-at.b887492af14bfe84f10cb2ff1b60acb0: "2024-12-05T14:03:47.131570189+00:00"
    restarter.stackable.tech/expires-at.ea77192c1184326d33e8ee32cfe921ea: "2024-12-05T15:49:10.043722965+00:00"
----

You can always determine the timestamp the Pod will be restarted by the xref:commons-operator:index.adoc[commons-operator] by taking the earliest timestamp, `2024-12-05T14:03:47.131570189+00:00` in this case.
This way you can verify that the changes you made to the temporary credentials lifetime take effect.
