= Authentication
:keycloak: https://www.keycloak.org/
:description: Overview of Stackable’s user authentication methods and configuration for LDAP, OIDC, TLS, and Static providers.

The Stackable Platform uses the AuthenticationClass as a central mechanism to handle user authentication across supported products.
The authentication mechanism needs to be configured only in the AuthenticationClass which is then referenced in the xref:stacklet.adoc[Stacklet] definition.
Multiple different authentication providers are supported.

[#authenticationclass]
== AuthenticationClass

The AuthenticationClass is a resource describing a generic authentication method like LDAP or Kerberos.
It has `cluster` scope, so it does not belong to a specific namespace.
Multiple operators use this CRD as a way to express and configure the authentication methods of their respective product.

The following authentication providers are supported:

* <<LDAP>>: Authenticate users using an LDAP server.
* <<OIDC>>: Authenticate users using an OpenID connect provider.
* <<TLS>>: Authenticate users with client TLS certificates.
* <<Kerberos>>: Authenticate users with Kerberos keytabs.
* <<Static>>: Authenticate users against a static list of users and passwords in a simple Kubernetes Secret.

[#ldap]
=== LDAP
A very simple AuthenticationClass with LDAP Authentication looks like this:

[source,yaml]
----
include::example$authenticationclass-ldap-simple.yaml[]
----
<1> The hostname of the LDAP server without any protocol or port
<2> The port of the LDAP server. If TLS is used it defaults to `636` otherwise to `389`
<3> An optional searchBase where the users should be searched
<4> The reference to the SecretClass for the bind credentials

In a diagram it would look like this:

image::image$authentication-overview.drawio.svg[]

NOTE: Learn more in the xref:tutorials:authentication_with_openldap.adoc[OpenLDAP tutorial] and get a full overview of all the properties in the {crd-docs}/authentication.stackable.tech/authenticationclass/v1alpha1/#spec-provider-ldap[AuthenticationClass LDAP provider CRD reference{external-link-icon}^].

[#OIDC]
=== OpenID Connect

An OIDC provider like {keycloak}[Keycloak{external-link-icon}^] could be configured as follows:

[source,yaml]
----
include::example$authenticationclass-keycloak.yaml[]
----

<1> Hostname of the identity provider.
<2> Port of the identity provider. If TLS is used defaults to 443, otherwise to 80.
<3> Root HTTP path of the identity provider. Defaults to `/`.
<4> Scopes to request from your identity provider. It is recommended to request the `openid`, `email`, and `profile` scopes.
<5> If a product extracts some sort of "effective user" that is represented by a string internally, this config determines which claim is used to extract that string.
<6> This is a hint about which identity provider is used by the AuthenticationClass.
<7> Optionally enable TLS and configure verification. When present, connections to the idP will use `https://` instead of `http://`. See xref:tls-server-verification.adoc[].
<8> Trust certificates signed by commonly trusted Certificate Authorities.

NOTE: Get a full overview of all the properties in the {crd-docs}/authentication.stackable.tech/authenticationclass/v1alpha1/#spec-provider-oidc[AuthenticationClass OIDC provider CRD reference{external-link-icon}^].

[#tls]
=== TLS
The `TLS` provider configures a product to authenticate users using TLS certificates.
When establishing a connection the client will first validate the certificate of the server.
This step is not influenced by this AuthenticationClass, it only affects the next step:
Afterwards the server checks the validity of the certificate the client has provided.
This includes the usual checks - such as checking that it hasn't expired and matches the hostname of the client.
Additionally the client certificate needs to be signed with the `ca` certificate, which is provided by the SecretClass specified in `clientCertSecretClass`.

A sample TLS provider looks as follows:

[source,yaml]
----
include::example$authenticationclass-tls.yaml[]
----

[#kerberos]
=== Kerberos
The `Kerberos` provider configures a product to authenticate users using Kerberos tickets issued by the Kerberos Key Distribution Center (KDC).
The Kerberos provider defines `kerberosSecretClass` which points to a Kerberos SecretClass that contains the necessary KDC and realm information:

[source,yaml]
----
include::example$authenticationclass-kerberos.yaml[]
----

[#static]
=== Static
The `static` provider is used to represent a simple - static - set of users.
Users are identified by a username and a password.

First, the AuthenticationClass needs to be defined as follows:

[source,yaml]
----
include::example$authenticationclass-static-authenticationclass.yaml[]
----
<1> The name of the Secret containing the credentials

Afterwards the referenced Secret needs to be created:

[source,yaml]
----
include::example$authenticationclass-static-secret.yaml[]
----
<1> The name of the Secret, which needs to match the Secret name specified in the AuthenticationClass above
<2> The namespace of the Secret. The Secret needs to be in the same namespace as the product that tries to use the static AuthenticationClass

[#further-reading]
== Further reading

* xref:tutorials:authentication_with_openldap.adoc[] tutorial
* {crd-docs}/authentication.stackable.tech/authenticationclass/v1alpha1/[AuthenticationClass CRD reference{external-link-icon}^]
