= Container images
:ubi: https://catalog.redhat.com/software/base-images
:multi-platform-images: https://docs.docker.com/build/building/multi-platform/
:stackable-image-registry: https://repo.stackable.tech/#browse/browse

The core artifacts of the Stackable Data Platform are container images or Docker images.
The operators as well as the deployed Stacklets are all running using container images.
All images deployed by the SDP are built by Stackable.

== Images overview

Every operator is packaged into its own image.
Every product is also packaged into its own image. 
Products that require multiple different processes to run, such as a coordinator and a worker, still only run off of one image.
Usually these products also only provide a single artifact that is used to run all processes.

Product images are built for xref:operators:supported_versions.adoc[] of products (Not all product versions are supported by all releases).

All images are stored in the {stackable-image-registry}[Stackable image registry].

== Image structure and contents

All our images are built using the {ubi}[Red Hat Universal Base Image (UBI)] minimal as a base image.
To support xref:ROOT:kubernetes.adoc[OpenShift], it is required to use a UBI base image.
The base image also contains only minimal dependencies and is vetted by RedHat.

The file system structure is the same across all images, which makes the images easier to work with.

Products are either built from scratch or official artifacts are used.
Beyond that, Stackable also adds plugins or extensions that are not shipped by default, to support features such as xref:operators:monitoring.adoc[] or xref:opa:index.adoc[OpenPolicyAgent] support.

[#multi-platform-support]
== Multi-platform support

Starting with Stackable release 24.7, all images are {multi-platform-images}[multi-platform images], supporting the AMD64 and ARM64 architectures.

== Why not use upstream images?

Some (but not all) products on the Stackable Data Platform already provide Docker images upstream.
For a number of reasons, Stackable does not support these upstream images; Stackable operators only work with Stackable product images (or images using these as base images).

* The structure across different product images upstream is different, which would mean using them would make operator development more difficult, but also would make it more difficult to work with the different images on the platform, as they would all be structured differently.
* Not all products supply images, so Stackable would already need to build _some_ container images for certain products.
* For the products that do provide images, the images are still lacking certain plugins or extensions for key features such as xref:operators:monitoring.adoc[] or xref:opa:index.adoc[OpenPolicyAgent support], or in some instances Stackable images contain patched products.
* For some of the products supported on the platform, there are also images distributed by the upstream project.

The operators also do not support all product versions and Stackable has its own xref:ROOT:policies.adoc[support policies] in place, which are also based on the particular versions that are supported.
