= Container images
:ubi: https://catalog.redhat.com/software/base-images
:multi-platform-images: https://docs.docker.com/build/building/multi-platform/
:stackable-image-registry: https://repo.stackable.tech/#browse/browse

The core artifacts of the Stackable Data Platform are container images or Docker images.
The operators as well as the deployed Stacklets are all running using container images.
All images deployed by the SDP are built by Stackable.

== Images overview

Every operator is packaged into its own image.
Every product is also packaged into its own image. 
Products that require multiple different processes to run, such as a coordinator and a worker, still only run off of one image.
Usually these products also only provide a single artifact that is used to run all processes.

Product images are built for xref:operators:supported_versions.adoc[] of products (Not all product versions are supported by all releases).

All images are stored in the {stackable-image-registry}[Stackable image registry].

== Image structure and contents

All our images are built using the {ubi}[Red Hat Universal Base Image (UBI)] minimal as a base image.
To support xref:ROOT:kubernetes.adoc[OpenShift], it is required to use a UBI base image.
The base image also contains only minimal dependencies and is vetted by RedHat.

The file system structure is the same across all images, which makes the images easier to work with.

Products are either built from scratch or official artifacts are used.
Beyond that, Stackable also adds plugins or extensions that are not shipped by default, to support features such as xref:operators:monitoring.adoc[] or xref:opa:index.adoc[OpenPolicyAgent] support.

[#multi-platform-support]
== Multi-platform support

All our images are {multi-platform-images}[multi-platform images], supporting the AMD64 and ARM64 architectures.

== Differences to upstream images

For some of the products supported on the platform, there are also images distributed by the upstream project.
However, Stackable operators do not work with these images, because Stackable operators expected a certain file system structure and in some cases additional scripts being present in the image.

Having Stackable built images means that all images share the same basic structure.
It also makes it possible to already include certain plugins and extensions (as mentioned above).

The operators also do not support all product versions and Stackable has its own xref:ROOT:policies.adoc[support policies] in place, which are also based on the particular versions that are supported.
