= Multi-Architecture for SDP

Today, we are proud to announce the next step in our efforts to port Stackable Data Platform (SDP) to the ARM64 architecture.

We arrived with 23.11.0 at a point where we are able to test and develop on a bare-metal ARM cluster. We have been using ARM-based instances on Azure and going forward are cooperating with HPE who have thankfully supplied us with resources to build and test Stackable Data Platform on multiple architectures, using their brand new and powerful Ampere-based hardware.

As this marks our beta phase, in this article we want to give an overview over the situation, a rough roadmap as well as a method to early access the 23.11.0 release for SDP on ARM64.

== State of the Art

At the moment we have a working 23.11.0 release. We made it publicly accessible but didn't merge it yet with the x86-64 releases you are already comfortable with.

Since this is new to us too, we have started by building the release manually and checking it for any defects when compared to the x86-64 release. To do so we are building a long-living soak test cluster where we perform updates and run workflows. We believe that most of the developed functionality on the x86-64 side can't be lost just by porting it to another architecture, and therefore we plan to focus on testing features which only can be seen on long-running clusters e.g. certificate rotation.

As a means of testing our 23.11.0 release we worked on our demos to make them accessible on ARM64. Those demos behaved as we expected compared to the same running on x86-64. This means, we have reworked the foundations of the demos and now you as a user can use them and work with SDP on your native cluster.

=== Actual Releases

We have currently one release on ARM64 which is 23.11.0.

We decided only to go for specific tags as we don't want to mess around with dev images. We could bundle them as a manifest list but decided to do that when we have an automated workflow and tests infrastructure in place. 

== Early-Access

As mentioned before, we have a working release 23.11.0 ported to the ARM64 architecture. Those images are stored within the `stackable-experimental` organization in our https://repo.stackable.tech/#browse/browse:docker:v2%2Fstackable-experimental[Nexus]. 

Accessing our data platform for ARM64 would mean needing to pull those images from the repo. As those are not available by default, you need to switch to the `stackable-experimental` organization. This needs to be done within the following two steps.

=== Early-Access with Helm

According to our https://docs.stackable.tech/home/stable/airflow/getting_started/installation#_helm[installation guide] you can install ARM64 operators e.g. for the commons operator as follows:

[source,bash]
----
helm install commons-operator stackable-stable/commons-operator --namespace stackable-operators --create-namespace --version=23.11.0 --set image.repository=docker.stackable.tech/stackable-experimental/commons-operator
----

The magic happens with `--set image.repository=docker.stackable.tech/stackable-experimental/commons-operator` `, here you overwrite the default image selection with the new organization stackable-experimental. The other operators can be installed in the same way by overriding the image repository.

WARNING: You have to install every operator you need for a given demo individually with helm using `--skip-release` with stackablectl. Otherwise, it will try to install x86 operators and pull ARM64 product images afterwards.

=== Early-Access to our products

Driven by the multi-architecture technology we introduced, the https://docs.stackable.tech/home/stable/concepts/product_image_selection[Product image selection] mechanism allows the user to choose a specific product image. This has some more advantages when you think about air-gapped environments or a mirrored repository. In our case we can use this feature to choose the ARM64 image as follows:

[source,yaml]
----
spec:
  image:
    custom: docker.stackable.tech/stackable-experimental/kafka:3.5.1-stackable23.11.0
    productVersion: 3.5.1
----
Once again, the key to success is to exchange `stackable` with `stackable-experimental` and point to the release 23.11.0.

NOTE: Only 23.11.0 is working at this moment.

=== Prepared Demos

You have seen there are  ways to access SPD demos for ARM64 architecture, but we had to rework some files. As we strive to provide our users the most comfortable deployment path we can, we have provided with a ready made branch to execute our demos on ARM64. We've provided below a complete set of instructions to make your ARM demo a success.

As a prerequisite, we expect you to have a Kubernetes Cluster of any flavour and stackablectl https://docs.stackable.tech/home/stable/quickstart[installed].

==== 1. Clone the demo repository
[source,bash]
----
git clone git@github.com:stackabletech/demos.git
----

==== 2. Checkout ARM64 demo branch ( release 23.11.0 )
[source,bash]
----
git pull && git checkout spike/demos-on-arm
----

==== 3. Install your demo with stackablectl (e.g. nifi-kafka-druid-earthquake-data)
[source,bash]
----
stackablectl demo install nifi-kafka-druid-earthquake-data --skip-release -s stacks/stacks-v2.yaml -d demos/demos-v2.yaml
----

== Road-Map

=== Release 23.7

This is an untested release on ARM64. All products besides Airflow and Superset are available and all operators are built.

Since still untested we released silently in stackable-experimental.

=== Release 23.11

Fairly untested release, not worked through yet.

We would suggest to build it the same way now as we did last time. On a local node and push and tag by hand. Additionally, we would like to take the opportunity to build a long-living test cluster for the release 23.11. This way, we could build a good amount (or the complete SDP platform) on an ARM-based cluster and do some efficient testing.

Our goal is would be to put in the effort to get all products and operators built and released as ARM64 images.

=== Between 23.11 and 24.3

Having an automatic workflow that builds multi-architecture dev releases into stackable-experimental all the time. While this is happening, I would like to update the test cluster with the dev versions and see if the newest changes do something to the ARM64 side of things.

This step can only be done if we have tested on 23.11.x and brought in all fixes necessary for SDP to function on ARM64.

=== Release 24.3

Tested release (with at least 80% coverage compared to x86-64). Multi-architecture builds get automatically released in the stackable-experimental repository at first. After sufficient testing I would like to go and finally merge stackable-experimental → stackable and having a first ever multi arch release. Still silent at this point, but documented.

=== Release 24.7

The "loud" multi arch release. From this point we would like SDP to be officially and fully tested on multi architecture.