= Multi-Architecture for SDP
:page-aliases: arm_support.adoc
:description: This page describes how to access ARM64 based SDP early
:keywords: Multi-Architecture, infrastructure, docker, image, tags, early-access

WARNING: This is an experimental feature of the Stackable Data Platform and yet under https://github.com/stackabletech/issues/issues/463[development].

== Early-Access

We have a working release 23.11.0 ported to the ARM64 architecture. Those images are stored within the `stackable-experimental` organization in our https://repo.stackable.tech/#browse/browse:docker:v2%2Fstackable-experimental[Nexus]. 

Accessing our data platform for ARM64 would mean needing to pull those images from the repo. As those are not available by default, you need to switch to the `stackable-experimental` organization.

=== Actual Releases

We have currently one release on ARM64 which is `23.11.0`.

We decided only to go for specific tags as we don't want to mess around with dev images. We could bundle them as a manifest list but decided to do that when we have an automated workflow and tests infrastructure in place. 

=== Early-Access with Helm

According to our https://docs.stackable.tech/home/stable/airflow/getting_started/installation#_helm[installation guide] you can install ARM64 operators e.g. for the commons operator as follows:

[source,bash]
----
helm install commons-operator stackable-stable/commons-operator --namespace stackable-operators --create-namespace --version=23.11.0 --set image.repository=docker.stackable.tech/stackable-experimental/commons-operator
----

The magic happens with `--set image.repository=docker.stackable.tech/stackable-experimental/commons-operator` `, here you overwrite the default image selection with the new organization stackable-experimental. The other operators can be installed in the same way by overriding the image repository.

WARNING: You have to install every operator you need for a given demo individually with helm using `--skip-release` with stackablectl. Otherwise, it will try to install x86 operators and pull ARM64 product images afterwards.

=== Early-Access to our products

Driven by the multi-architecture technology we introduced, the https://docs.stackable.tech/home/stable/concepts/product_image_selection[Product image selection] mechanism allows the user to choose a specific product image. This has some more advantages when you think about air-gapped environments or a mirrored repository. In our case we can use this feature to choose the ARM64 image as follows:

[source,yaml]
----
spec:
  image:
    custom: docker.stackable.tech/stackable-experimental/kafka:3.5.1-stackable23.11.0
    productVersion: 3.5.1
----
Once again, the key to success is to exchange `stackable` with `stackable-experimental` and point to the release 23.11.0.

NOTE: Only 23.11.0 is working at this moment.

=== Prepared Demos

You have seen there are  ways to access SPD demos for ARM64 architecture, but we had to rework some files. As we strive to provide our users the most comfortable deployment path we can, we have provided with a ready made branch to execute our demos on ARM64. We've provided below a complete set of instructions to make your ARM demo a success.

As a prerequisite, we expect you to have a Kubernetes Cluster of any flavour and stackablectl https://docs.stackable.tech/home/stable/quickstart[installed].

==== 1. Clone the demo repository
[source,bash]
----
git clone git@github.com:stackabletech/demos.git
----

==== 2. Checkout ARM64 demo branch ( release 23.11.0 )
[source,bash]
----
cd demos && git pull && git checkout spike/demos-on-arm
----
==== 3. Install stackable operators ( release 23.11.0 )
NOTE: Executing a script where all operators of 23.11.0 are installed. You can omit this step and only install operators you want by copying the corresponding `helm` command.

[source,bash]
----
./arm.sh
----
==== 4. Install your demo with stackablectl (e.g. nifi-kafka-druid-earthquake-data)
[source,bash]
----
stackablectl demo install nifi-kafka-druid-earthquake-data --skip-release -s stacks/stacks-v2.yaml -d demos/demos-v2.yaml
----
