= Concepts
:description: Explore Stackable Data Platform concepts like Stacklets, configuration mechanisms, resources, connectivity, security, and observability.

== Overview

The xref:overview.adoc[Platform overview] is a good starting point to understand the Stackable Data Platform covering the overall architecture, deployement and configuration.

== General configuration mechanisms

Learn what a xref:stacklet.adoc[Stacklet] is, what roles and role groups are, and how product image selection works.
There is also the common xref:overrides.adoc[override] mechanism for configuration settings, although this tool should be used with care!

== Resources

Learn about how xref:resources.adoc[] are configured; this covers CPU, memory and storage.
Learn about how xref:s3.adoc[] are configured across the platform.
Learn about how to access xref:experimental-arm64-support[ARM64-support].

== Connectivity

Many Platform components depend on other components or expose functionality that you can connect to.
This connectivity is achived with xref:service-discovery.adoc[service discovery ConfigMaps].
To access your Stackable operated products from outside the Kuberenetes cluster learn more about xref:service-exposition.adoc[].

== Security

Security aspects include xref:authentication.adoc[authenticating] users when services are accessed and subsequently xref:opa.adoc[authorizing] access to operations and data inside of the services.
It also includes xref:tls-server-verification.adoc[].

== Operations

The xref:operations/index.adoc[operations] section is directed at platform maintainers.
It covers xref:operations/cluster_operations.adoc[starting, stopping and restarts] of products, xref:operations/graceful_shutdown.adoc[] and other topics related to maintenance and ensuring stability of the platform operation.

== Observability

Learn about which xref:labels.adoc[labels] are attached to the operators and the stacklets and the resources that get created by the operator.
Also learn about xref:logging.adoc[].
