= Labels

Labels are key/value pairs in the metadata of Kubernetes objects that add identifying information to the object.
They do not have direct semantic implications but can be used to organize and manage resources.
stackablectl, the cockpit and the Helm Charts add labels to the resources that are part of a Stacklet, and the operators add labels to the resources they create.

== Resource labels added by the operators

Every resource created by a Stackable operator is labelled with a common set of labels.
Some of these labels are https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/[recommended] to use by the Kubernetes documentation.
These are the labels that are added:

- `app.kubernetes.io/name` - The name of the product, i.e. `druid` or `zookeeper`.
- `app.kubernetes.io/version` - The version of the product, i.e. `3.3.4`
- `app.kubernetes.io/instance` - The name of the Stacklet.
- `app.kubernetes.io/component` - This is the xref:concepts:roles-and-role-groups.adoc[role] that this resource belongs to.
- `app.kubernetes.io/role-group` - The name of the xref:concepts:roles-and-role-groups.adoc[role group] that a resource belongs to.
- `app.kubernetes.io/managed-by` - Which software manages this resource? This will be the operator, i.e. `airflow-operator`.

also this:

- `stackable.tech/vendor` with value `Stackable`


== Labels added by tooling

* each operator is labeled with "vendor" (and other recommended labels)

=== stackablectl

* when using stackablectl
** stacks and demos
*** all manifests that are part of stacks/demos have a label for that attached. I.e. configmaps, secrets, volumes ....
**** vendor label; dynamic labels: stackablectl was used; part of which stack/demo it is
*** Helm installs (i.e. postgres, redis etc.): ... nothing yet
*** operator installs: operators installed as part of a stack/demo are labeled
*** all the other recommended labels are still applied to resources




=== Helm

* The Helm charts for the operators support adding your own labels to them
** all _templated resources_ (Deployment, ClusterRole, ...) get these labels



== Read more

ADR: https://docs.stackable.tech/home/nightly/contributor/adr/adr031-resource-labels

// what would be nice to have:
//
// * custom labels
// * operators labeling their resources as part of a stack too