= Multi-platform for SDP
:keywords: Multi-Architecture, infrastructure, docker, image, tags
:multi-platform-images: https://docs.docker.com/build/building/multi-platform/
:description: Starting with Stackable 24.7, all images support AMD64 and ARM64 architectures, enabling mixed clusters with architecture-specific tags and automated selection.

WARNING: This status is still experimental, as we work to fine-tune the necessary workflows.

Starting with the Stackable Data Platform release 24.7, all images are {multi-platform-images}[multi-platform images], supporting the AMD64 and ARM64 architectures.
Each product image is built for each platform with an architecture-specific tag.
For example, the Airflow images with tags `airflow:2.9.2-stackable24.7.0-amd64` and `airflow:2.9.2-stackable24.7.0-arm64` are bundled in the manifest list `airflow:2.9.2-stackable24.7.0` using an automated workflow.
The appropriate image will then be transparently selected for the active platform/architecture.
This also enables mixed Kubernetes clusters, with AMD64 and ARM64 nodes being used simultaneously.

NOTE: Superset 2.x (deprecated, and to be removed in a future version) is not available as a multi-platform product image.
