:source-highlighter: highlight.js
:highlightjs-languages: rust

= OPA authorization

The Stackable Platform offers policy-based access control via the https://www.openpolicyagent.org[OpenPolicyAgent] (OPA) operator.
//
Policies are defined in the Rego language, divided into packages and supplied via ConfigMaps.
//
Every node is running an OPA instance for fast policy evaluation and products are connected to OPA with the xref:service_discovery.adoc[service discovery] mechanism.

== What is OPA?
// What's OPA? What are Rego Rules?
OPA is an open source, general purpose policy engine. It supports a high-level declarative language called https://www.openpolicyagent.org/docs/latest/policy-language/[Rego]. Rego enables you to specify complex policies as code and transfer the decision-making processes from your software to OPA. Policies written in Rego are called _Rego rules_.

// policy requests
Policy requests are made to a REST API. In the request the requester can supply arbitrary structured input data as JSON to supply context information. For example the name of the user, resource and action for which an authorization is requested. In this way policy decision-making and policy enforcement are decoupled.

== How it works on the stackabe platform
// How it is deployed
OPA is run by the xref:opa::index.adoc[Stackable OPA operator]. OPA is deployed with the OpaCluster resource, from which the operator creates a DaemonSet to run an OPA instance on every node of the cluster. Because of this, every other Pod making policy requests will always make the request locally, minimizing latency.

=== Define policies

// Rego rules in config maps
The Rego rule policies are supplied as ConfigMaps. Multiple ConfigMaps can be used for multiple packages, for example one ConfigMap per product. ConfigMaps are easy to create. The operator takes care of assembling the ConfigMaps into a policy bundle. Every policy ConfigMap needs to be labeled so the operator knows to include it.

Here's an example of a Rego rule package in a ConfigMap:

[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-product-policies
  labels:
    opa.stackable.tech/bundle: "my-product" <1>
data:
  my-product.rego: |
    package my-product <2>

    import future.keywords.in

    default allow = false <3>
    allow {
      is_admin
    }

    is_admin() { <4>
      input.context.identity.user == "admin"
    }
----

<1> The `opa.stackable.tech/bundle` label is needed to add this ConfigMap to the OPA policy set. Only ConfigMaps with this label are included.
<2> `my-product` is the name of the package. Usually you will have one package per product or per product instance. The name of the package needs to be configured in product instances (i.e. a Trino or Druid instance). The product will use the policies from the configured policy package.
<3> The `allow` rule. It is the main entry point. For every policy decision, the `allow` rule is always requested. In this case, the rule defaults to `false`. It references the `is_admin` rule.
<4> the `is_admin` rule. It demonstrates the use of context information. Every policy decision request can supply context, in this case the user identity is supplied as context. Only if the user identity is "admin", the `is_admin` rule evaluates to true.

The combination of arbitrary input data and the Rego rules enable you to specify and enforce almost any kind of policies.
You can define powerful policies for e.g. user access for database tables, schemas, columns etc. You can enforce local network traffic, access time periods and many more.

See the https://www.openpolicyagent.org/docs/latest/#overview[OPA documentation] for further examples.

=== Connect a product

// discovery
The OpaCluster is also discoverable via the xref:service_discovery.adoc[service discovery mechanism]. To use OPA authorization you simply need the name of the OpaCluster to connect to and the name of the policy package to use.


A product that supports OPA authorization will have a part of the spec like this

[yaml,source]
----
opa:
  configMapName: simple-opa <1>
  package: my-product <2>
----
<1> The reference to the OPA cluster
<2> The name of the policy package to use for this product


== Further reading

These products support OPA authorization for now:

* xref:trino::usage.adoc#_authorization[Trino]
* xref:kafka::usage.adoc[Kafka]
* xref:druid::usage.adoc#_using_open_policy_agent_opa_for_authorization[Druid]

You can also have a look at our xref:contributor:opa_configuration.adoc[implementation guidelines for OPA authorizers].