= Product image selection

All the Stackable Data Platform products run on Kubernetes.
Every container - which executes the actual product - needs a docker image to run of.
The docker images contain the actual products as well as some other tools needed to operate them.
Therefore choosing an image influences which version of the product wil be started.

There are multiple ways to specify the docker image used:

== Stackable provided images
If your Kubernetes cluster has internet access, the easiest way is to use the publicly available Images from the https://docker.stackable.tech/[Image registry hosted by Stackable].
If the Kubernetes cluster does not have internet access, a xref:_custom_docker_registry[] or xref:_custom_images[] can be used.

Currently you need to specify two versions:

1. **Product version:** The version of the product, as it e.g. can be found on the xref:operators:supported_versions.adoc[list of supported product versions] or on the website of the product itself.
2. **Stackable version:** As we need to make changes to the Images, we also have to version them using the Stackable version.
All the available images (with their product and stackable version) can be found in our https://repo.stackable.tech/#browse/browse:docker:v2%2Fstackable[docker repository].

The versions need to be specified on Stackable products as follows:

[source,yaml]
----
spec:
  image:
    productVersion: 3.3.1
    stackableVersion: 0.1.0
----

== Custom docker registry
Custom docker registries can be used to fetch the image from a local image registry rather than from the internet.
The perquisite is that you mirror all the needed images the same way (with the same name and tag) as the image provided by Stackable.

Afterwards you can use the following snippet to configure your custom docker repo:

[source,yaml]
----
spec:
  image:
    productVersion: 3.3.1
    stackableVersion: 0.1.0
    repo: my.corp/myteam/stackable
----

This will change the image from e.g. `docker.stackable.tech/stackable/kafka:3.3.1-stackable0.1.0` to `my.corp/myteam/stackable/kafka:3.3.1-stackable0.1.0`.

== Custom images
Custom images can be used to fetch the image from a local image registry rather than from the internet.
The difference in comparison to the xref:_custom_docker_registry[] is, that this option is the most flexible, as an arbitrary image can be specified.
If your image has other tags or names than the ones provided by Stackable you need to use this option.

[source,yaml]
----
spec:
  image:
    custom: my.corp/myteam/stackable/kafka:latest-and-greatest
    productVersion: 3.3.1
----

The operators need to make decisions based upon the product version - e.g which config properties are supported as of which version.
Therefore they need to know the product version that is contained within the image.
It's your responsibility to put in the correct product version in here.
