= Resource management

The Stackable Data Platform and its xref:operators:index.adoc[operators] deploy their products in https://kubernetes.io/docs/concepts/containers/[containers] within https://kubernetes.io/docs/concepts/workloads/pods/[Pods] using https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/[StatefulSets] or https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSets].
In order for the Kubernetes scheduler to select a suitable https://kubernetes.io/docs/concepts/architecture/nodes/[Node] for a Pod, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource] requests and limits for CPU and memory can be specified.
The Kubernetes scheduler ensures that the sum of the CPU and memory requests does not exceed the capacity of a given Node.

== Terminology

The most commonly defined resources are CPU and memory (RAM).
Keep in mind that there are other resources as well.
For more information have a look at the Kubernetes https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits[documentation] on resources.

=== CPU

==== Requests

The CPU request defines which containers are allowed to have more CPU resources.
Larger requests lead to more CPU resources than smaller requests if not enough resources are available.

==== Limits

The CPU limit is a hard bound on how much CPU resources the container can use.
The Linux kernel checks to see if the limit is exceeded and waits if this is the case to resume the process.

=== Memory

==== Requests

The memory request is used during Kubernetes scheduling and checks which Nodes offer sufficient memory for a Pod to be scheduled.

==== Limits

The memory limit is a hard bound.
If a container tries to use more memory than specified, the container is usually marked for restart.
To avoid the restart it is critical to specify sufficient resources.

=== Storage

Some Stackable products require data storage.
This is done using https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims[Persistent Volume Claims] where the size of storage can be specified.

== Kubernetes resource requests

In Kubernetes, you can specify resource requests and limits within containers of Pods.

[source, yaml]
----
---
apiVersion: v1
kind: Pod
metadata:
  name: stackable
spec:
  containers:
  - name: stackable
    image: stackable:0.1.0
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
----

This Pod/container will be scheduled on a Node that has at least `64Mi` of free memory.
It is allowed to use a maximum amount of `128Mi` of memory or will be restarted if this value is exceeded.
It can not use more CPU resources than `500m` (which is half of a physical or virtual core), but has a guaranteed CPU resources of `250m`.

== Stackable resource requests

=== CPU and memory

include::stackable_resource_requests.adoc[]

=== Storage

This is an example on how to specify storage resources using the Stackable https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resources]:

[source, yaml]
----
---
apiVersion: example.stackable.tech/v1alpha1
kind: ExampleCluster
metadata:
  name: example
spec:
  workers: # role-level
    config:
      resources:
        storage:
          data: # name of the storage
            capacity: 3Gi
    roleGroups: # role-group-level
      resources-from-role: # role-group 1
        replicas: 1
      resources-from-role-group: # role-group 2
        replicas: 1
        config:
          resources:
            storage:
              data: # name of the storage
                capacity: 4Gi
----

In this case, the role group `resources-from-role` will inherit the resources specified on the role level.
Resulting in a `3Gi` storage space for `data`.

The role group `resources-from-role-group` has maximum of `4Gi` storage space for `data` (which overrides the role resources).

IMPORTANT: Stackable operators use different names (`data` in this example) for their storage specification. This is documented in the operator specific documentation.

[#storageclass]
==== StorageClass

A StorageClass defines a type of storage with certain properties.
The StorageClasses that are available on a Kubernetes cluster are configured by the cluster administrator.
Different classes can be configured to provide different levels of reliability or speed, or be configured to be more suited for read or write heavy loads.
This configuration is either done in the storage backend or Kubernetes settings (find more information in the https://kubernetes.io/docs/concepts/storage/storage-classes/[Kubernetes documentation]).

For Stackable resources, setting a StorageClass is not mandatory; if not StorageClass is set, the https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass[default StorageClass] will be used.
If you want to use a specific StorageClass for a particular storage, the StorageClass can be set on the resource:

[source,yaml]
----
...
resources:
  storage:
    data: # name of the storage
      capacity: 4Gi
      storageClass: my-storage-class
----
