= S3 resources

// -------------- Intro ----------------

Many of the tools on the Stackable platform integrate with S3 storage in some way. For example reading data from an S3 data source or using S3 as a temporary or long term storage.

// TODO: which tools exactly support S3 as of now?
For example, Druid can ingest data from S3 and also use S3 as a backend for deep storage. Hive ... TODO

// -------------- Introducing the objects ------------

In the Stackable platform we deal with _S3Connections_ and _S3Buckets_.
// s3 connection
An S3Connection contains information on how to connect to a server serving an S3 object storage. This includes the host name, port, TLS parameters and also access credentials.
// s3 bucket
An S3Bucket contains a reference to an S3Connection, the connection to the server where the bucket is located. An S3Connection can be referenced by multiple buckets. The besides the connection, the bucket object just contains the name of the bucket.

== Object Structure
// ---------- Referencing -------------

S3Buckets reference S3Connections. Both types of objects are referenced in other resources. For example: In a DruidCluster you can specify a bucket for deep storage and an S3Connection to be used for ingestion of data.
Every object can always be specified as a dedicated object or inlined into the enclosing object.

[excalidraw,s3-cluster-bucket-connection-reference,svg,width=70%]
----
include::partial$diagrams/S3ResourceOverview.excalidraw[]
----

The diagram above shows three examples of how the objects can be
 structured.
// Option 1
In option 1 all objects are separate. This gives you maximum flexibility and reusability. If the same connection or bucket should be referenced in a different object, the bucket/connection is already there. You can also have different people in your team manage product cluster, buckets and connection separately.
// Option 2
In option 2 the bucket is inlined in the cluster definition. This makes sense if you have a dedicated bucket for a specific purpose, if it is only used in this one cluster instance, in this single product.
// Option 3
Option 3 shows all objects inlined. This is the most convenient to quickly test something. Everything is in a single manifest. If you quickly want to spin up a DruidCluster, just specify everything inline.

=== Examples

To clarify the concept, a few examples will be given, using a DruidCluster resource as an example.

[source,yaml]
----

apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: my-druid-cluster
spec:
  deepStorage:
    # to be defined ...
  # more spec here ...
----

To save space, we will only write the `deepStorage` part of the cluster definition in the examples below.

Access credentials for buckets will be explained in their own section in <TODO>.

==== Inline definition

The inline definition is variant 3 in the figure above.

[excalidraw,s3-cluster-bucket-connection-reference,svg,width=70%]
----
include::partial$diagrams/S3ResourcesInlined.excalidraw[]
----

The advantage is, that everything is defined in a single file, right where it is going to be used:

[source,yaml]
----

apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: my-druid-cluster
spec:
  deepStorage:
      s3:
        inline: # <1>
          bucketName: my-bucket
          connection:
            inline: # <2>
              host: test-minio
              port: 9000
  # more spec here ...
----
<1> The inline definition of the bucket. The bucket definition contains `bucketName` and `connection`.
<2> The inline definition of the connection. It contains the `host` and `port`.


==== Dedicated resources

Often multiple buckets are used across a data pipeline, as well as buckets being used by different applications, so dedicated resource definitions that can be referenced from multiple objects make sense.

[excalidraw,s3-cluster-bucket-connection-reference,svg,width=70%]
----
include::partial$diagrams/S3ResourcesByReference.excalidraw[]
----

The DruidCluster references the S3Bucket, which in turn references the S3Connection. First the definition of the S3Connection:

[source,yaml]
----
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: my-connection-resource
spec:
  host: s3.example.com
  port: 4242
----

Then the bucket, which references the connection:


[source,yaml]
----
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Bucket
metadata:
  name: my-bucket-resource
spec:
  bucketName: my-example-bucket
  connection:
    reference: my-connection-resource
----

You can then use this bucket, for example in Druid, as a deep storage:

[source,yaml]
----

apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: my-druid-cluster
spec:
  deepStorage:
      s3:
        reference: my-bucket-resource
  # more spec here ...
----

== Credentials


No matter if a connection is specified inline or as a separate object, the credentials are always specified in the same way. You will need a `Secret` containing the access key ID and secret access key, a `SecretClass` and then a reference to this `SecretClass` where you want to specify the credentials.

The `Secret`:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  labels:
    secrets.stackable.tech/class: s3-credentials-class  # <1>
stringData:
  accessKey: YOUR_VALID_ACCESS_KEY_ID_HERE
  secretKey: YOUR_SECRET_ACCES_KEY_THATBELONGS_TO_THE_KEY_ID_HERE
----

<1> This label connects the `Secret` to the `SecretClass`.

The `SecretClass`:

[source,yaml]
----
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: s3-credentials-class
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
----

Referencing it:

[source,yaml]
----
...
credentials:
  secretClass: s3-credentials-class
...
----

== What's next

- Find details about the options of the S3 resource in the xref:reference:s3.adoc[S3 resources reference].
- Find usage examples of S3 in _Druid_, _Hive_, ... .
