= Service exposition
:listener-operator: xref:listener-operator:index.adoc
:secret-operator: xref:secret-operator:index.adoc
:listenerclass: xref:listener-operator:listenerclass.adoc
:description: Explore how Stackable utilizes the listener-operator to expose Services.

Data products expose interfaces to the outside world.
These interfaces (whether UIs, or APIs) can be accessed by other products or by end users.
Clients accessing the interfaces can run inside or outside of the same Kubernetes cluster.
For example, xref:zookeeper:index.adoc[Apache ZooKeeper] is a dependency for other products, and it usually needs to be accessible only from within Kubernetes, while xref:superset:index.adoc[Apache Superset] is a data analysis product for end users and therefore needs to be accessible from outside the Kubernetes cluster.
Users connecting to Superset can be restricted within the local company network, or they can connect over the internet depending on the company security policies and demands.
This page gives an overview over the different options for service exposition, when to choose which option and how these options are configured.

== Motivation

Service exposition is such a complicated topic, that Stackable has build it's own operator for that: {listener-operator}[].
The following section explains the motivation behind implementing such an operator instead of using plain regular Kubernetes Services.

=== Products advertising their addresses

Some products require information about their external accessibility.
This is e.g. important for HDFS, where the namenode keeps track of which datanode serves which block. Another case is Kafka, where it is required for client bootstrapping.
A common use case is an HDFS client connecting to a namenode in order to read block 42. Therefore, the namenode needs to know which datanode is serving block 42. The namenode then responds with the IP or hostname of the datanode containing that block 42.
For that to work, the datanode needs to know it's external address on startup and tell it the namenode.
(And yes, we needed to patch the Hadoop sourcecode for that)

The {listener-operator}[listener-operator] runs as CSI driver (same as the {secret-operator}[secret-operator]) and places files inside the CSI volume, which tell the tool how it is reachable.

=== Integration with {secret-operator}[secret-operator]

If a tool is secured using TLS or Kerberos, it does not only need to be reachable via the determined address, it also needs a TLS certificate/keytab issued on the determined address.
{secret-operator}[secret-operator] integrated with to {listener-operator}[listener-operator], so that the platform takes care of provisioning certificates with the correct addresses (in the form of SAN entries).

== {listenerclass}[ListenerClasses]

A {listenerclass}[] describes how a product should be exposed.
Please read on {listenerclass}[its documentation] before continuing on this page.

As a quick reminder, the platform ships with 3 default {listenerclass}[ListenerClasses]:

`cluster-internal`:: Used for listeners that are only accessible internally from the cluster. For example: communication between ZooKeeper nodes.
`external-unstable`:: Used for listeners that are accessible from outside the cluster, but which do not require a stable address. For example: individual Kafka brokers.
`external-stable`:: Used for listeners that are accessible from outside the cluster, and do require a stable address. For example: Kafka bootstrap.

Keep in mind that you are not restricted to this list, you can configure your own custom {listenerclass}[ListenerClasses].

== Configuring the ListenerClass for a Stacklet

The {listener-operator}[listener-operator] is integrated into most of the Stackable products, currently only xref:opa:index.adoc[] and xref:spark-k8s:index.adoc[] are not using {listener-operator}[listener-operator].

Most of the tools configure the {listenerclass}[] at the role level as follows:

[source,yaml]
----
spec:
  my-role:
    roleConfig:
      listenerClass: external-unstable
----

Every operator has a documentation section called "Service exposition with ListenerClasses", which may provide details for the specific tool.
