---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  version: 1.5.1-stackable0.3.0
  statsdExporterVersion: v0.22.4
  credentialsSecret: superset-credentials
  nodes:
    roleGroups:
      default:
        config:
