name: Flag Nexus upload

on:
  pull_request:
    types: [ closed ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:
      - name: Create closed marker
        run: touch closed
      - name: Delete PR build
        if: env.NEXUS_PASSWORD != null # pragma: allowlist secret
        run: >-
          curl --fail --user 'github:${{ secrets.NEXUS_PASSWORD }}'
          --upload-file closed
          https://repo.stackable.tech/repository/misc/docs/pr${{ github.event.pull_request.number }}/closed
